file(GLOB_RECURSE SOURCES ${CMAKE_CURRENT_LIST_DIR}/../src/*)

# Generate .rc file.
if(MSVC)
	if (NOT DEFINED VTX_VERSION_MAJOR)
		set(VTX_VERSION_MAJOR 0)
	endif()
	if (NOT DEFINED VTX_VERSION_MINOR)
		set(VTX_VERSION_MINOR 0)
	endif()
	if (NOT DEFINED VTX_VERSION_PATCH)
		set(VTX_VERSION_PATCH 0)
	endif()

	set(VERSION_STRING "${VTX_VERSION_MAJOR}.${VTX_VERSION_MINOR}.${VTX_VERSION_PATCH}.0")
	string(REPLACE "." "," VERSION_COMMA "${VERSION_STRING}")
	string(TIMESTAMP YEAR "%Y")
	set(COPYRIGHT "Copyright (C) ${YEAR}")
	set(FILENAME "VTX.rc")
	file(COPY ${CMAKE_CURRENT_LIST_DIR}/../asset DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
	configure_file(${CMAKE_CURRENT_LIST_DIR}/../asset/windows_resources/VTX.rc.in ${CMAKE_CURRENT_BINARY_DIR}/asset/windows_resources/VTX.rc @ONLY)	

	file(GLOB_RECURSE RESOURCES ${CMAKE_CURRENT_BINARY_DIR}/asset/windows_resources/*.rc)
endif()

add_executable(vtx ${SOURCES} ${RESOURCES})
configure_target(vtx)
link_cuda(vtx)

if (NOT DEFINED _VTX_CONAN)
	target_link_libraries(vtx PRIVATE vtx_util)
	target_link_libraries(vtx PRIVATE vtx_core)
	target_link_libraries(vtx PRIVATE vtx_renderer)
	target_link_libraries(vtx PRIVATE vtx_io)
	target_link_libraries(vtx PRIVATE vtx_app)
	target_link_libraries(vtx PRIVATE vtx_python_binding)
	target_link_libraries(vtx PRIVATE vtx_ui_qt)
	target_link_libraries(vtx PRIVATE vtx_tool_example)
	target_link_libraries(vtx PRIVATE vtx_tool_mdprep)
else()
	target_link_libraries(vtx PRIVATE vtx_util::vtx_util)
	target_link_libraries(vtx PRIVATE vtx_core::vtx_core)
	target_link_libraries(vtx PRIVATE vtx_renderer::vtx_renderer)
	target_link_libraries(vtx PRIVATE vtx_io::vtx_io)
	target_link_libraries(vtx PRIVATE vtx_app::vtx_app)
	target_link_libraries(vtx PRIVATE vtx_python_binding::vtx_python_binding)
	target_link_libraries(vtx PRIVATE vtx_ui_qt::vtx_ui_qt)
	target_link_libraries(vtx PRIVATE vtx_tool_example::vtx_tool_example)
	target_link_libraries(vtx PRIVATE vtx_tool_mdprep::vtx_tool_mdprep)
endif()

target_link_libraries(vtx PRIVATE Qt6::Core)
target_link_libraries(vtx PRIVATE Qt6::Gui)
target_link_libraries(vtx PRIVATE Qt6::Widgets)
target_link_libraries(vtx PRIVATE Qt6::OpenGLWidgets)

# Declare preprocessor definitions.
if (NOT DEFINED VTX_TOOL_EXAMPLE)
	set(VTX_TOOL_EXAMPLE 0)
endif()
if (NOT DEFINED VTX_TOOL_MDPREP)
	set(VTX_TOOL_MDPREP 1)
endif()

target_compile_definitions(vtx PRIVATE VTX_TOOL_EXAMPLE=${VTX_TOOL_EXAMPLE})
target_compile_definitions(vtx PRIVATE VTX_TOOL_MDPREP=${VTX_TOOL_MDPREP})

vtx_register_build_directory_copy("${CMAKE_CURRENT_LIST_DIR}/../data" "./data")
vtx_copy_registered_data(vtx) # allow declared files to be copied on build
