file(GLOB_RECURSE SOURCES ${CMAKE_CURRENT_LIST_DIR}/../src/*)

# Default values for options.
if (NOT DEFINED VTX_VERSION_MAJOR)
	set(VTX_VERSION_MAJOR 0)
endif()
if (NOT DEFINED VTX_VERSION_MINOR)
	set(VTX_VERSION_MINOR 0)
endif()
if (NOT DEFINED VTX_VERSION_PATCH)
	set(VTX_VERSION_PATCH 0)
endif()
if (NOT DEFINED VTX_TOOL_EXAMPLE)
	set(VTX_TOOL_EXAMPLE 0)
endif()
if (NOT DEFINED VTX_TOOL_MDPREP)
	set(VTX_TOOL_MDPREP 1)
endif()

# Generate .rc file.
if(MSVC)
	

	set(VERSION_STRING "${VTX_VERSION_MAJOR}.${VTX_VERSION_MINOR}.${VTX_VERSION_PATCH}.0")
	string(REPLACE "." "," VERSION_COMMA "${VERSION_STRING}")
	string(TIMESTAMP YEAR "%Y")
	set(COPYRIGHT "Copyright (C) ${YEAR}")
	set(FILENAME "VTX.rc")
	file(COPY ${CMAKE_CURRENT_LIST_DIR}/../asset DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
	configure_file(${CMAKE_CURRENT_LIST_DIR}/../asset/windows_resources/VTX.rc.in ${CMAKE_CURRENT_BINARY_DIR}/asset/windows_resources/VTX.rc @ONLY)	

	file(GLOB_RECURSE RESOURCES ${CMAKE_CURRENT_BINARY_DIR}/asset/windows_resources/*.rc)
endif()

add_executable(vtx ${SOURCES} ${RESOURCES})
vtx_configure_target(vtx)
vtx_link_cuda(vtx)

if(UNIX AND NOT APPLE)
	set_target_properties(vtx PROPERTIES INSTALL_RPATH "$ORIGIN")
endif()

if (NOT DEFINED _VTX_CONAN)
	target_link_libraries(vtx PRIVATE vtx_util)
	target_link_libraries(vtx PRIVATE vtx_app)
	target_link_libraries(vtx PRIVATE vtx_ui_qt)
	if (VTX_TOOL_EXAMPLE)
		target_link_libraries(vtx PRIVATE vtx_tool_example)
	endif()
	if (VTX_TOOL_MDPREP)
		target_link_libraries(vtx PRIVATE vtx_tool_mdprep)
	endif()
else()
	target_link_libraries(vtx PRIVATE vtx_util::vtx_util)
	target_link_libraries(vtx PRIVATE vtx_app::vtx_app)
	target_link_libraries(vtx PRIVATE vtx_ui_qt::vtx_ui_qt)
	if (VTX_TOOL_EXAMPLE)
		target_link_libraries(vtx PRIVATE vtx_tool_example::vtx_tool_example)
	endif()
	if (VTX_TOOL_MDPREP)
		target_link_libraries(vtx PRIVATE vtx_tool_mdprep::vtx_tool_mdprep)
	endif()
endif()

# Declare preprocessor definitions.
target_compile_definitions(vtx PRIVATE VTX_TOOL_EXAMPLE=${VTX_TOOL_EXAMPLE})
target_compile_definitions(vtx PRIVATE VTX_TOOL_MDPREP=${VTX_TOOL_MDPREP})

vtx_renderer_copy_shaders(vtx)
vtx_python_binding_copy_runtime(vtx)
vtx_qt_copy_runtime(vtx)
if (VTX_TOOL_MDPREP)
	vtx_tool_mdprep_copy_data(vtx)
endif()
