#ifndef __VTX_APP_INTERNAL_MATH_ENUM_TRANSFORM__
#define __VTX_APP_INTERNAL_MATH_ENUM_TRANSFORM__

#include <util/generic/enum_flag.hpp>

namespace VTX::App::Internal::Math
{
	enum class TRANSFORM_COMPOSANT_ENUM : int
	{
		TRANSLATE_X = 1 << 0,
		TRANSLATE_Y = 1 << 1,
		TRANSLATE_Z = 1 << 2,

		TRANSLATE_VECTOR = TRANSLATE_X | TRANSLATE_Y | TRANSLATE_Z,

		EULER_X = 1 << 3,
		EULER_Y = 1 << 4,
		EULER_Z = 1 << 5,

		EULER_VECTOR = EULER_X | EULER_Y | EULER_Z,

		SCALE_X = 1 << 6,
		SCALE_Y = 1 << 7,
		SCALE_Z = 1 << 8,

		SCALE_VECTOR = SCALE_X | SCALE_Y | SCALE_Z,

		TRANSFORM = TRANSLATE_VECTOR | EULER_VECTOR | SCALE_VECTOR,
		NONE	  = 0,
	};

	VTX_FLAG( TRANSFORM_COMPOSANT_MASK, TRANSFORM_COMPOSANT_ENUM )
} // namespace VTX::App::Internal::Math

#endif
