#ifndef __VTX_RENDERER_CONTEXT_GL_INCLUDE_OPENGL__
#define __VTX_RENDERER_CONTEXT_GL_INCLUDE_OPENGL__

#include <glad/gl.h>

#define VTX_OPENGL_MAJOR_VERSION 4
#define VTX_OPENGL_MINOR_VERSION 6

#endif
