#version 450 core
#include "include/helper.glsl"
#include "../constant.glsl"

#ifndef LOCAL_SIZE_X
	#define LOCAL_SIZE_X 1
#endif
#ifndef LOCAL_SIZE_Y
	#define LOCAL_SIZE_Y 1
#endif
#ifndef LOCAL_SIZE_Z
	#define LOCAL_SIZE_Z 1
#endif

layout (local_size_x = LOCAL_SIZE_X, local_size_y = LOCAL_SIZE_Y, local_size_z = LOCAL_SIZE_Z) in;

// Uniforms.
uniform uint uSize;

// SSBO.
layout (std140, binding = 0) buffer Normals
{
	vec4[] normals;
};

layout (std140, binding = 1) readonly buffer NormalsCasted
{
	ivec4[] normalsCasted;
};

void main()
{
	uint hash = globalInvocationHash( gl_GlobalInvocationID, gl_NumWorkGroups, gl_WorkGroupSize );
	
	if( hash >= uSize )
	{
		return;
	}

	const vec3 normal = vec3(   normalsCasted[ hash ].x,
								normalsCasted[ hash ].y,
								normalsCasted[ hash ].z );
	
	/*
	const vec3 normal = vec3(   intBitsToFloat( normalsCasted[ hash ].x ),
								intBitsToFloat( normalsCasted[ hash ].y ),
								intBitsToFloat( normalsCasted[ hash ].z ) );
	*/

	normals[ hash ] = vec4( normalize( normal ), 0.f );
}