message("vtx_ui_qt")
cmake_minimum_required(VERSION 3.23)
project(vtx_ui_qt)

if (NOT DEFINED VTX_RENDERER)
	set(VTX_RENDERER 1)
endif()
if (NOT DEFINED VTX_PYTHON_BINDING)
	set(VTX_PYTHON_BINDING 1)
endif()

find_package(vtx_util CONFIG REQUIRED)
find_package(vtx_app CONFIG REQUIRED)
find_package(vtx_core CONFIG REQUIRED)
if (VTX_RENDERER)
	find_package(vtx_renderer CONFIG REQUIRED)
endif()
if (VTX_PYTHON_BINDING)
	set(PYBIND11_PYTHON_VERSION "${CPYTHON_VERSION_MAJOR}.${CPYTHON_VERSION_MINOR}.${CPYTHON_VERSION_PATCH}")
	find_package(Python3 "${CPYTHON_VERSION_MAJOR}.${CPYTHON_VERSION_MINOR}.${CPYTHON_VERSION_PATCH}" EXACT REQUIRED COMPONENTS Interpreter Development NO_SYSTEM_ENVIRONMENT_PATH)
	find_package(vtx_python_binding CONFIG REQUIRED)
endif()
find_package(Qt6 CONFIG COMPONENTS Core REQUIRED)
find_package(Qt6 CONFIG COMPONENTS Gui REQUIRED)
find_package(Qt6 CONFIG COMPONENTS Widgets REQUIRED)

set(_VTX_UI_QT_CONAN " ") # So the right target name can be linked
include("./cmake/library.cmake")

install(TARGETS vtx_ui_qt FILE_SET public_headers DESTINATION include)
vtx_install_build_modules()
vtx_qt_install_runtime(vtx_ui_qt)
