#ifndef __VTX_APP_OLD_ID__
#define __VTX_APP_OLD_ID__

#include <string>

namespace VTX::App::Old
{
	using VTX_ID = std::string;

	namespace ID
	{
		namespace Model
		{
			const VTX_ID MODEL_MOLECULE					= "MODEL_MOLECULE";
			const VTX_ID MODEL_CATEGORY					= "MODEL_CATEGORY";
			const VTX_ID MODEL_CHAIN					= "MODEL_CHAIN";
			const VTX_ID MODEL_RESIDUE					= "MODEL_RESIDUE";
			const VTX_ID MODEL_ATOM						= "MODEL_ATOM";
			const VTX_ID MODEL_BOND						= "MODEL_BOND";
			const VTX_ID MODEL_SECONDARY_STRUCTURE		= "MODEL_SECONDARY_STRUCTURE";
			const VTX_ID MODEL_SOLVENT_EXCLUDED_SURFACE = "MODEL_SOLVENT_EXCLUDED_SURFACE";
			const VTX_ID MODEL_GENERATED_MOLECULE		= "MODEL_GENERATED_MOLECULE";
			const VTX_ID MODEL_MESH_TRIANGLE			= "MODEL_MESH_TRIANGLE";
			const VTX_ID MODEL_PATH						= "MODEL_PATH";
			const VTX_ID MODEL_VIEWPOINT				= "MODEL_VIEWPOINT";
			const VTX_ID MODEL_SELECTION				= "MODEL_SELECTION";

			const VTX_ID MODEL_REPRESENTATION_LIBRARY	  = "MODEL_REPRESENTATION_LIBRARY";
			const VTX_ID MODEL_INTANTIATED_REPRESENTATION = "MODEL_INTANTIATED_REPRESENTATION";

			const VTX_ID MODEL_REPRESENTATION = "MODEL_REPRESENTATION";

			const VTX_ID MODEL_RENDERER_RENDER_EFFECT_PRESET_LIBRARY = "MODEL_RENDERER_RENDER_EFFECT_PRESET_LIBRARY";
			const VTX_ID MODEL_RENDERER_RENDER_EFFECT_PRESET		 = "MODEL_RENDERER_RENDER_EFFECT_PRESET";

			const VTX_ID MODEL_LABEL						   = "LABEL";
			const VTX_ID MODEL_MEASUREMENT_DISTANCE			   = "MEASUREMENT_DISTANCE";
			const VTX_ID MODEL_MEASUREMENT_DISTANCE_TO_CYCLE   = "MEASUREMENT_DISTANCE_TO_CYCLE";
			const VTX_ID MODEL_MEASUREMENT_ANGLE			   = "MEASUREMENT_ANGLE";
			const VTX_ID MODEL_MEASUREMENT_DIHEDRAL_ANGLE	   = "MEASUREMENT_DIHEDRAL_ANGLE";
			const VTX_ID MODEL_MEASUREMENT_MEASURE_IN_PROGRESS = "MODEL_MEASUREMENT_MEASURE_IN_PROGRESS";
		} // namespace Model

		namespace View
		{
			const VTX_ID INSTANTIATED_REPRESENTATION_ON_REPRESENTATION
				= "INSTANTIATED_REPRESENTATION_ON_REPRESENTATION";
			const VTX_ID REPRESENTATION_LIBRARY_ON_ITEMS = "REPRESENTATION_LIBRARY_ON_ITEMS";

			const VTX_ID RENDER_EFFECT_LIBRARY_ON_ITEMS = "RENDER_EFFECT_LIBRARY_ON_ITEMS";
			const VTX_ID D3_CYLINDER					= "3D_CYLINDER";
			const VTX_ID D3_SPHERE						= "3D_SPHERE";
			const VTX_ID D3_BOX							= "3D_BOX";
			const VTX_ID D3_TRIANGLE					= "3D_TRIANGLE";
			const VTX_ID D3_RIBBON_PATCH				= "3D_RIBBON_PATCH";
			const VTX_ID D3_TRIANGLE_SES				= "3D_TRIANGLE_SES";
		} // namespace View

		// TODO Check if these IDs should be here or in VTX_UI
		namespace State
		{
			const VTX_ID VISUALIZATION = "VISUALIZATION";
			const VTX_ID PLAY		   = "PLAY";
			const VTX_ID EXPORT		   = "EXPORT";
		} // namespace State

		// TODO Check if these IDs should be here or in VTX_UI
		namespace Controller
		{
			const VTX_ID FREEFLY	 = "FREEFLY";
			const VTX_ID TRACKBALL	 = "TRACKBALL";
			const VTX_ID ORBIT		 = "ORBIT";
			const VTX_ID SHORTCUT	 = "SHORCUT";
			const VTX_ID VESSEL		 = "VESSEL";
			const VTX_ID PICKER		 = "PICKER";
			const VTX_ID MEASUREMENT = "MEASUREMENT";
			const VTX_ID MAIN_WINDOW = "MAIN_WINDOW";

		} // namespace Controller
	}	  // namespace ID
} // namespace VTX::App::Old

#endif
