#ifndef __VTX_APP_OLD_EVENT_MODEL__
#define __VTX_APP_OLD_EVENT_MODEL__

#include "app/old/core/event/vtx_event.hpp"

namespace VTX::App::Old::Event
{
	// Model events for notifier pattern (model->views)[1-n].
	enum Model : Core::Event::VTX_EVENT
	{
		INIT,
		DATA_CHANGE,
		MOLECULE_VISIBILITY,
		CATEGORY_VISIBILITY,
		CHAIN_VISIBILITY,
		RESIDUE_VISIBILITY,
		ATOM_VISIBILITY,
		VISIBILITY,
		TRANSFORM_CHANGE,
		REPRESENTATION_CHANGE,
		COLOR_CHANGE,
		DISPLAY_NAME_CHANGE,
		QUICK_ACCESS_CHANGE,
		SUBITEM_DATA_CHANGE,
		REPRESENTATION_TYPE_CHANGE,
		TRAJECTORY_FRAME_CHANGE,
		TRAJECTORY_DATA_CHANGE,
		AUTO_ROTATE_DATA_CHANGE,
		APPLIED_PRESET_CHANGE,
	};

} // namespace VTX::App::Old::Event
#endif
