function( configure_qt )
	set( CMAKE_AUTOMOC ON PARENT_SCOPE )
endfunction()

function( add_resources p_target p_path p_target_name)
	file(GLOB_RECURSE QT_RESOURCES ${p_path}/*)
	message(-----------------------------------------------------------)
	message(-----------------------------------------------------------)
	message(-----------------------------------------------------------)
	message(-----------------------------------------------------------)
	message(-----------------------------------------------------------)
	message(-----------------------------------------------------------)
	message(-----------------------------------------------------------)
	message(-----------------------------------------------------------)
	message(-----------------------------------------------------------)
	
	message(-----------------------------------------------------------)
	message(${p_target_name})
	qt_add_resources( ${p_target} ${p_target_name} BASE ${p_path} FILES ${QT_RESOURCES} )
endfunction()