function( vtx_qt_add_resources p_target p_path p_resource_name)
	file(GLOB_RECURSE QT_RESOURCES ${p_path}/*)
	qt_add_resources( ${p_target} ${p_resource_name} BASE ${p_path} FILES ${QT_RESOURCES} OUTPUT_TARGETS RESOURCE_TARGET )
	set_property(TARGET ${RESOURCE_TARGET} PROPERTY FOLDER "resources")
	if(TARGET ${p_target}_other_files)
		set_property(TARGET ${p_target}_other_files PROPERTY FOLDER "other")
	endif()
	target_link_libraries(${p_target} PRIVATE ${RESOURCE_TARGET})
endfunction()
