
#include "core/chemdb/category.hpp"

namespace VTX::Core::ChemDB::Category
{
	Dictionary createDefaultDictionary()
	{
		Dictionary out;

		out.vocabularies[ static_cast<uint>( TYPE::POLYMER ) ]
			= { "NVA", "HMF", "KY7", "DNE", "EW6", "ASL", "SUB", "QO8", "3BY", "CYA", "SWG", "C99", "Q3P", "VDL", "2CO",
				"CGH", "MCG", "AKL", "RC7", "TYI", "0AF", "SHR", "B3S", "OXX", "19W", "13E", "PRO", "3EG", "MF3", "3O3",
				"NIY", "TRG", "MEA", "OMY", "LLP", "HNC", "CSX", "FC0", "6GL", "GND", "DHN", "DNS", "LAA", "BHD", "KCX",
				"MH8", "B3T", "2DO", "4PH", "OEM", "CLE", "PAT", "4U7", "PNZ", "TYC", "IGL", "UAL", "HS9", "MFC", "CME",
				"GZJ", "LCX", "ARF", "PDW", "GHW", "N10", "ALY", "KCY", "0AB", "HLY", "KNB", "XX1", "DA2", "0A0", "2KY",
				"NEP", "MD5", "PRS", "N65", "BB9", "WLU", "5XU", "SIB", "GSU", "DLS", "6BR", "GLY", "4SJ", "9DS", "5LE",
				"DAB", "CSR", "HIP", "3PM", "CCY", "LA2", "6G4", "2SO", "26B", "G01", "2QD", "BB8", "TQI", "PRV", "AHH",
				"HM8", "VLM", "B3Y", "2ML", "3AH", "OMZ", "MJ1", "HOX", "TDF", "DNM", "BTC", "IPG", "3GL", "C1T", "NMC",
				"TPO", "0XL", "B2H", "2AS", "DYJ", "CYG", "QNQ", "DSN", "TZB", "MOD", "73P", "AR2", "B3U", "2QY", "9V0",
				"MGY", "TYJ", "C6C", "03Y", "S1H", "0TH", "TH5", "FTR", "NYG", "SEB", "7C9", "DAR", "HTI", "MCS", "KBE",
				"DIL", "PYA", "LEM", "5GG", "5CW", "MP4", "PE1", "OLE", "FIO", "11W", "CSU", "DFF", "F93", "POM", "5R5",
				"OSE", "OLT", "6KY", "PTR", "KZY", "5HP", "LRK", "BTA", "R4K", "MA",  "2TL", "CAF", "NLO", "GGL", "LPL",
				"28J", "CMT", "MSO", "4BF", "2HF", "BE2", "IEL", "P2Q", "SOY", "2LU", "LLZ", "0XQ", "EJA", "CML", "DTY",
				"LPH", "ML3", "HSO", "CYR", "0YG", "FGL", "2YJ", "4HH", "PYH", "6HN", "F7V", "HIQ", "B3E", "DTR", "M6J",
				"SVY", "F7P", "EYG", "STY", "MLU", "HSV", "PRK", "IYR", "4HT", "KGC", "TSQ", "R6E", "SEC", "04X", "CXM",
				"XDT", "00B", "PCC", "66D", "EXA", "APK", "ILE", "0W6", "2L9", "CCL", "FCL", "A0G", "LYX", "MSL", "GCM",
				"2KK", "DBZ", "0AH", "OHI", "FQA", "CLD", "MC1", "BIU", "3YM", "DDE", "SBD", "HJV", "1E3", "HOO", "TRQ",
				"81R", "TEF", "OLZ", "P4E", "YYA", "00E", "PVO", "OLD", "QPH", "MIR", "DTH", "3K4", "31Q", "UXY", "VYA",
				"KYQ", "HPC", "ILM", "Q3S", "TYY", "7YO", "ECC", "GNC", "6YJ", "BG1", "MHS", "2PI", "SEM", "LAL", "RVJ",
				"C4R", "1OP", "ASN", "JJK", "GLZ", "CTH", "SEL", "HTY", "2AD", "4N3", "5VV", "56C", "M3L", "0A2", "GSC",
				"3XH", "BBC", "BH2", "YCM", "CRW", "2ZC", "NZH", "BJH", "ASP", "B3L", "TXY", "MFV", "34E", "51T", "UY7",
				"RON", "J9Y", "0WZ", "RVX", "MHE", "XPL", "0QL", "MKD", "5MW", "4F3", "1X6", "DSP", "J3D", "QNY", "ACA",
				"GT9", "LYM", "APO", "YOF", "55N", "DPQ", "2R3", "HQA", "DFI", "N7P", "NTY", "060", "LEF", "LNM", "FVA",
				"PM3", "32L", "TTS", "B2N", "MDO", "PHL", "4AR", "F2Y", "FLA", "ORD", "AB7", "6Y9", "ZAL", "DHI", "MNV",
				"9NE", "LYU", "KZG", "ZAE", "Q75", "NWD", "FGP", "RE3", "BF9", "KY4", "41H", "HSL", "TY1", "I58", "CMH",
				"XYC", "LPD", "GLH", "AEI", "PBB", "CSB", "MMO", "TRO", "3MD", "CDV", "4OP", "HIX", "P9S", "PRR", "KBV",
				"04V", "TY3", "AYA", "ONH", "SEE", "PH6", "O6H", "MSP", "PR7", "TOZ", "2P0", "0QZ", "TY9", "UN1", "TYB",
				"CRG", "N0A", "CYQ", "G3M", "LGY", "MET", "VAH", "45W", "7O5", "85J", "KHB", "DYL", "KJW", "2OR", "05N",
				"MAI", "GAU", "MIS", "CLB", "RGL", "QFG", "4J4", "9NV", "AHB", "HGL", "PBF", "CIR", "CGV", "MEG", "OBF",
				"PSH", "SNM", "LET", "TFR", "MHV", "SHC", "BL2", "32S", "1TQ", "OHS", "LEH", "9E7", "0AK", "CLG", "6V1",
				"DMK", "EHP", "PQ4", "V44", "UYA", "APM", "CJO", "41Q", "LYV", "RT0", "AIB", "MYK", "ARO", "QNW", "3CF",
				"CSY", "NEM", "MVA", "V61", "1C3", "SET", "S2P", "TFQ", "KZ7", "B2C", "FTY", "DJD", "J9A", "JLP", "8JB",
				"MEN", "D11", "23S", "TBM", "CHG", "9VF", "PQG", "NPH", "NBQ", "I1C", "CR0", "R0E", "2L5", "ESB", "ALS",
				"QC4", "0UZ", "CY4", "NPI", "HHK", "DHA", "IEY", "FPK", "O2E", "AA3", "1TY", "TYX", "HHI", "TMD", "GLX",
				"MPH", "CSE", "TYN", "C66", "DAL", "6V9", "CNG", "CYJ", "EXY", "4N9", "9KP", "432", "MNL", "SVZ", "QDS",
				"C3Y", "CRO", "ME0", "TYS", "PCE", "00O", "4NT", "NLN", "5FQ", "U6A", "LEI", "SD4", "01N", "F75", "08M",
				"0AA", "2JC", "QVA", "BTK", "PH8", "0RJ", "8LJ", "L3O", "MFH", "T11", "CSZ", "CZZ", "IIL", "F0G", "EEP",
				"2RX", "DVA", "22G", "M3V", "G1X", "4CG", "OTZ", "NZC", "4HJ", "QLG", "TOX", "CR5", "QQB", "02L", "4M8",
				"DHP", "ZYK", "AGT", "ORN", "FB5", "4IN", "UNK", "02K", "9EV", "ALM", "MYN", "CG6", "OMT", "MLE", "BIF",
				"SKG", "1ME", "CZS", "HT7", "6FL", "CY0", "Z70", "LEU", "ZCL", "3PX", "SE7", "KZV", "FFM", "193", "FZN",
				"IML", "4OV", "CRK", "DSE", "UU4", "M3R", "TY2", "SAR", "DNP", "9MN", "0FL", "IAS", "LYR", "TLY", "JKH",
				"5A6", "1U8", "BUG", "DGN", "0CS", "GYC", "CSK", "GHC", "TSY", "DAH", "E0Y", "HG7", "SLZ", "LYS", "TNR",
				"UDS", "LYF", "MHL", "OZW", "E03", "4J2", "XSN", "3AR", "037", "BYR", "GVL", "ICY", "GL3", "SVV", "32T",
				"DPN", "LBZ", "PHE", "AHP", "TNQ", "KFP", "73C", "NHL", "DHL", "G5G", "MGG", "PSW", "175", "6DU", "AME",
				"PHD", "IYT", "J7H", "VLL", "6CW", "ARM", "OIC", "IAR", "PHI", "NLY", "CSO", "CSA", "6KM", "0E5", "UM2",
				"DPL", "2R1", "WVL", "4LZ", "8RE", "FHO", "0TD", "0EH", "C22", "9VC", "4II", "ZBZ", "MDF", "4AF", "OZT",
				"ILX", "9U6", "GHP", "KCJ", "TCR", "MBQ", "30F", "F9D", "CS1", "YTH", "PDD", "0A1", "0X9", "NDF", "RE0",
				"CUC", "CFY", "T9E", "2RA", "O7A", "DPP", "7J4", "PHA", "MD0", "3ZL", "LSO", "CSD", "UU5", "EME", "UKD",
				"CS3", "4L0", "TQZ", "OAS", "ALT", "HRG", "3GA", "DOH", "KPF", "1PI", "0AC", "LVN", "FY3", "RZ4", "I4G",
				"CH7", "1G8", "4CY", "HM9", "CE7", "PIA", "WFP", "HFA", "WPA", "DC2", "2JJ", "FME", "J8W", "CGA", "NSK",
				"L2A", "TS9", "BCS", "4MM", "60F", "KST", "MD6", "9U0", "FDL", "ASK", "K7K", "1JM", "F7Q", "F7S", "LEN",
				"R2P", "P3Q", "KKD", "BF6", "ONL", "LWY", "LME", "G8M", "HPQ", "CPI", "PIV", "OTB", "CRF", "TQQ", "SNN",
				"SEN", "6CL", "EOE", "2YF", "UB4", "HS8", "K1R", "2JF", "A8E", "AZY", "GMO", "1TX", "3NF", "LVG", "N9P",
				"OHD", "9VL", "VR0", "LLY", "PG1", "AA6", "143", "F6N", "6CV", "ZYJ", "MPQ", "30V", "TRX", "1AC", "E95",
				"3QN", "ARV", "OBS", "MHO", "NOT", "R1A", "ESC", "API", "GMA", "S2C", "4KY", "BMT", "FPR", "UN2", "CLH",
				"MH6", "TAV", "N2C", "TCQ", "IAM", "SHP", "ABA", "THZ", "S2D", "Y28", "T0I", "4NU", "QO5", "QCA", "XXA",
				"THO", "QYG", "0BN", "LED", "GLQ", "UMA", "66C", "AAR", "ZFB", "MDH", "3ZH", "2XA", "HLU", "PFX", "AGQ",
				"FLE", "LKE", "HLX", "ACB", "SGB", "Z3E", "AE5", "FL6", "DBU", "FT6", "9NF", "2AO", "K5H", "SAO", "5LB",
				"9BP", "QNT", "TPJ", "DM0", "EXL", "35Y", "200", "DMH", "UZN", "P4F", "UKY", "CSJ", "562", "FGA", "LYZ",
				"MSA", "FHL", "DCY", "3A5", "MLL", "CZO", "5AB", "DLE", "NLB", "Q2E", "4CF", "ASQ", "IZO", "7JA", "THR",
				"DBB", "CH6", "BNN", "U3X", "NCY", "V1V", "GEE", "PYL", "1G3", "TY5", "ADD", "PRJ", "85F", "OMH", "ZZU",
				"K5L", "3WS", "MEQ", "KZ4", "CS4", "04U", "F2F", "BCX", "4PQ", "B27", "02V", "TYE", "PYX", "OV7", "HAC",
				"1L1", "823", "AGM", "SMC", "2QZ", "NTR", "LPS", "LNE", "TYO", "9AT", "HTN", "4FB", "CQ2", "B8R", "AC5",
				"CWR", "E9C", "NAM", "ZZJ", "1MH", "CAS", "2JG", "DYA", "LBY", "CSW", "PG9", "PFF", "LLO", "LDH", "LYH",
				"SCH", "SER", "5CR", "QQ8", "UM1", "SME", "PAS", "01W", "4AK", "OYL", "HR7", "MP8", "AS2", "9UC", "TIS",
				"EFC", "TYR", "5SQ", "3X9", "99Y", "4D4", "CYS", "VOL", "7N8", "81S", "NYC", "D2T", "NLP", "X9Q", "LTA",
				"MME", "TYQ", "MH1", "6E4", "M2L", "7MN", "5OH", "9R4", "NAL", "BTR", "PCA", "07O", "CGU", "11Q", "KCR",
				"KOR", "9VR", "SKJ", "5DW", "F3M", "CAB", "5OM", "MPJ", "PPN", "5OL", "KZ1", "JJL", "BSE", "02Y", "4HL",
				"4AW", "12L", "CTE", "M64", "1XW", "TZO", "ARG", "HRP", "O7D", "YPZ", "0A8", "4DP", "0GG", "A9D", "12X",
				"U2X", "7CC", "KPI", "QZA", "IOR", "9NR", "GYS", "ASB", "4IK", "HVA", "WCR", "0G5", "DNG", "RPI", "JBY",
				"FRD", "B3A", "NCB", "NNH", "AEA", "CY3", "LCK", "MND", "DGH", "YPR", "SLL", "PR3", "2TY", "NFA", "9KK",
				"NLQ", "4QK", "N80", "CZ2", "04R", "CSP", "PGY", "DMT", "TH6", "CEA", "KXV", "TST", "33S", "HGY", "73O",
				"NRG", "4FW", "LYO", "TTQ", "ASM", "ALO", "4J5", "OCY", "BWB", "AS7", "M30", "XXY", "CYD", "X2W", "BIL",
				"EYS", "VH0", "UOX", "P1L", "P2Y", "XW1", "RGP", "ORQ", "ETA", "IIC", "QX7", "192", "HIS", "PLJ", "CYW",
				"CYM", "QO2", "LP6", "9R7", "EUP", "7HA", "FOD", "VAF", "4UD", "BB7", "TNB", "NRQ", "HYP", "OJY", "08P",
				"5T3", "DHV", "CYF", "N8P", "KPY", "AZK", "A5N", "HCM", "85G", "IOY", "PVL", "NMM", "DAS", "F7W", "B3K",
				"00C", "VMS", "CWD", "PTM", "MHY", "C1X", "AJE", "GLM", "AS9", "1PA", "CR7", "TRF", "ACL", "CPC", "1VR",
				"DON", "KEO", "5GM", "0EA", "HIC", "UGY", "0MU", "4N8", "56A", "HL2", "TNY", "TRY", "TRP", "BWV", "Q78",
				"GLN", "SBL", "DYS", "3FG", "GLU", "OGZ", "MGN", "28X", "C5C", "PEC", "D3P", "03E", "GFT", "SMF", "CRQ",
				"ILG", "PVH", "CR8", "ALA", "HTR", "T8L", "0AZ", "HJY", "0Y9", "4N7", "NKS", "DI8", "BF7", "DAM", "TBG",
				"5OW", "02O", "SIC", "6WK", "CDE", "CRU", "OIM", "AZS", "UIA", "B3M", "I2M", "6M6", "AN8", "S12", "SFE",
				"BPE", "23F", "33W", "FY2", "7XC", "OCS", "ZUK", "1G2", "PXU", "C0O", "SUI", "2YC", "5CT", "PAQ", "9DN",
				"DIR", "ASI", "MEU", "HBN", "NRP", "LYN", "9TU", "OTH", "TGH", "HL5", "NYS", "LWI", "ZIQ", "XOK", "KYN",
				"LV8", "KWS", "2SI", "DSG", "TMB", "TRN", "DOA", "4GJ", "LTR", "MHW", "SEG", "9TX", "PRQ", "TPK", "AR4",
				"CLV", "DI7", "6RK", "CR2", "D4P", "DO2", "ECX", "LMF", "SEP", "AA4", "HJH", "B3X", "MT2", "4DB", "DFO",
				"PTH", "LHC", "ALC", "9UF", "DLY", "2GX", "SKH", "NLW", "MK8", "2JN", "62H", "QMM", "CCS", "SCS", "TA4",
				"0Y8", "5PG", "SCY", "H5M", "LE1", "ZZD", "0NC", "AVN", "QCS", "UZ4", "TPL", "AZH", "2JH", "MD3", "DBY",
				"NLE", "23P", "HV5", "QIL", "2KP", "DNL", "0LF", "APP", "APH", "KBS", "73N", "TIH", "SXE", "8SP", "5ZA",
				"LMQ", "GME", "URV", "TOQ", "CSH", "E9V", "TY8", "SVW", "EO2", "SNC", "UZA", "5LF", "FF9", "HAR", "QXV",
				"SOC", "9WV", "CRX", "CSS", "12Y", "TDD", "SLR", "2VA", "SRZ", "U2M", "FH7", "M0H", "O12", "GHG", "MLY",
				"Z01", "HCS", "2YH", "SUN", "CAY", "ASX", "FOE", "HSE", "BB6", "M2S", "SNK", "0AR", "MHU", "ALN", "MTY",
				"02A", "DIV", "PCS", "VAD", "DPR", "2YG", "HGM", "3TY", "IT1", "SD2", "999", "VB1", "B3Q", "CQR", "LPG",
				"SDP", "66E", "CS0", "DDZ", "MSE", "THC", "B1F", "TPH", "5X8", "DV7", "XYG", "CHP", "9R1", "4WQ", "XPR",
				"ELY", "AFA", "9TR", "UX8", "7J3", "BUC", "NA8", "WZJ", "DYG", "HMR", "2MR", "2LT", "TPQ", "BP5", "HPE",
				"PR4", "SYS", "3MM", "2FM", "FHE", "MAA", "2MT", "FP9", "8YR", "UF0", "GPL", "C2N", "6ZS", "C12", "DBS",
				"2L6", "FB6", "A66", "9U9", "O7G", "2AG", "L5P", "33X", "MED", "MLZ", "MV9", "H14", "CUD", "ZU0", "WRP",
				"0XO", "FLT", "AHO", "SVA", "SVX", "XCN", "OTY", "4L8", "QPA", "4OG", "54C", "ZGL", "MCL", "QAC", "ASA",
				"VAL", "PF5", "GZB", "5CS", "LOU", "0A9", "3CT", "DNW", "BXT", "JJJ", "DGL", "GLJ", "D0Q", "8WY", "P0A",
				"YNM", "R2T", "SAC", "G8X", "TRW", "2KZ", "BW5", "MOZ", "NB8", "AGD", "OFM", "YCP", "T66", "NC1", "QCD",
				"3MY", "E9M", "004", "BJO", "4FO", "CY1", "HIA", "AYG", "HY3", "9V6", "POK", "HSK", "LAY", "TYT", "PR9",
				"0PR", "HCL", "FAK", "SAH", "HZP", "RF9", "F3T", "BZK", "CQ1", "BFD", "PDL", "1IP", "OMX", "AN6", "4OU",
				"74P", "NYB" };
		out.vocabularies[ static_cast<uint>( TYPE::ION ) ]
			= { "SO3", "CR",  "NRU", "OH",	"TB",  "NA5", "MO2", "VO4", "GEP", "NAO", "PT4", "AL",	"CUA", "CAC", "3NI",
				"PB",  "PDV", "AM",	 "PT",	"CU3", "TBA", "OCL", "MW2", "ZO3", "W",	  "AU",	 "NI2", "PO3", "CHT", "VN3",
				"EMC", "E4N", "OF2", "SB",	"3CO", "CUZ", "CO3", "HAI", "LU",  "MG",  "MO6", "EU3", "SO4", "ZN",  "CL",
				"AZI", "MMC", "IUM", "SEK", "BF4", "IR",  "IN",	 "HG",	"THE", "6MO", "1CU", "OC5", "ZN2", "RHD", "MN",
				"ALF", "OC6", "ZN3", "NET", "MLI", "MN3", "ZCM", "OAA", "4MO", "OF3", "AUC", "MO1", "MOO", "CD1", "FE2",
				"CD5", "MAC", "3OF", "SR",	"2HP", "DSC", "OS",	 "LI",	"OF1", "RB",  "3MT", "OHX", "Y1",  "UNX", "CS",
				"PD",  "RU",  "PR",	 "OC2", "4PU", "OC1", "MO5", "TL",	"LCO", "OC4", "GA",	 "OCM", "NI3", "CYN", "YB",
				"OS4", "CO5", "SE4", "OCO", "543", "SM",  "MO4", "AU3", "PI",  "LA",  "CU1", "4TI", "T1A", "KO4", "IR3",
				"BA",  "BCT", "NI1", "PBM", "OC3", "OXL", "CA",	 "DME", "BR",  "CE",  "NA",	 "1AL", "K",   "MN6", "ATH",
				"CF",  "SMO", "NI",	 "TRA", "OC8", "TH",  "RH3", "BSY", "FPO", "OCN", "MN5", "FE",	"MW1", "NO3", "ZR",
				"MH3", "V",	  "MW3", "2OF", "F",   "2FK", "TEA", "CON", "ER3", "HGC", "IRI", "OC7", "O4M", "MOS", "DTI",
				"YT3", "YB2", "GD3", "MO3", "NA2", "NH4", "SCN", "AG",	"DY",  "BS3", "CU",	 "TMA", "PTN", "CD",  "CO",
				"NCO", "TCN", "YH",	 "CD3", "PO4", "3P8", "PER", "ZNO", "118", "119", "NO2", "NA6", "MOW", "BEF", "MH2",
				"WO5", "BO4", "ACT", "IOD", "LCP", "EU",  "NAW", "DMI", "EDR" };
		out.vocabularies[ static_cast<uint>( TYPE::WATER ) ]  = { "HOH", "WAT", "SOL", "MTO", "DOD", "DIS" };
		out.vocabularies[ static_cast<uint>( TYPE::LIGAND ) ] = { "" };
		out.vocabularies[ static_cast<uint>( TYPE::CARBOHYDRATE ) ]
			= { "NGR", "5FC", "1SC", "DGU", "JSV", "DP",  "FNY", "X34", "DQQ", "GP4", "DFG", "4AM", "CAP", "14T", "2L8",
				"BBV", "KTU", "SMP", "PKM", "A1P", "C6G", "SZZ", "TH1", "XAL", "LFR", "N5M", "XCR", "SOG", "ZBC", "DXN",
				"XYP", "GL1", "CNU", "T0N", "ERE", "6GP", "BGS", "WZ2", "RTG", "A5M", "FNU", "ASC", "DHU", "6MA", "B9D",
				"HN0", "DPB", "YYK", "PZG", "RB5", "B8D", "GL4", "SDD", "DDX", "PVX", "MM7", "GS4", "CAR", "77Y", "OAK",
				"DO8", "DT6", "IDF", "GLA", "XAE", "U23", "2DA", "1BW", "CE5", "U9A", "XDP", "CGY", "AMV", "TCJ", "AFF",
				"2M5", "2BD", "ZCD", "T2T", "42D", "2ST", "TTV", "A6C", "T",   "F73", "G6D", "I",	"BMP", "9PG", "0R8",
				"LKC", "31H", "DRP", "KGV", "OSU", "A2G", "SIZ", "C38", "AIG", "5UA", "27C", "RM4", "SOE", "GUF", "PDU",
				"M1Y", "NGE", "GAL", "1JB", "6MJ", "RUU", "C31", "G35", "Z9N", "F8X", "LZ0", "EUS", "LCA", "8OS", "128",
				"F7H", "OOB", "JMH", "0G",	"5AA", "KDE", "2BT", "6PO", "UFP", "A6A", "AHR", "JVS", "NG1", "ROR", "9T7",
				"VJ4", "THM", "34V", "MXY", "RDG", "XCT", "XGA", "F3H", "EWC", "CM0", "PRP", "C4X", "STW", "SG6", "IDC",
				"9KJ", "EMZ", "1RN", "1GL", "F6X", "P5P", "4DG", "Z4V", "GPK", "491", "BDG", "127", "ASG", "1W5", "AGR",
				"LB2", "4E9", "LVZ", "PST", "SAY", "ZB2", "T5O", "7D1", "EBQ", "SR1", "DU",	 "LXC", "6HT", "AFG", "F3O",
				"GTH", "CEX", "DQR", "XBP", "RST", "BXX", "2FP", "ABS", "FAX", "2PR", "PNJ", "RSQ", "GC4", "1X4", "5MD",
				"TOA", "EHG", "PPU", "G7P", "22O", "GMZ", "3ZO", "RWI", "A6P", "FA5", "H3S", "CFZ", "6MT", "KME", "SMD",
				"6CT", "LNV", "2OT", "OMG", "DG0", "ISL", "X1P", "FSA", "AAO", "0AV", "8B7", "7AT", "2GT", "OKQ", "OTN",
				"Z61", "DP5", "MA1", "F6P", "GSD", "PRN", "5KV", "C34", "3YW", "DZ",  "FFD", "WC7", "D4B", "X5S", "YIO",
				"F7X", "Z",	  "DKZ", "ZDU", "26R", "SSG", "GCB", "73E", "SMT", "NCX", "2NT", "SG5", "PTQ", "DL6", "WZ1",
				"2MG", "3DA", "KDM", "T6T", "16G", "GLG", "SWE", "GCN", "Z3U", "NGY", "SLT", "6NW", "DX",  "C25", "7DA",
				"A9Z", "CH",  "XYL", "GPH", "574", "5PC", "HEU", "TF0", "SDE", "A40", "TNX", "DJF", "UFR", "LEC", "A1Q",
				"SA0", "TCP", "SOR", "ARB", "G0S", "MFT", "JDT", "TFF", "ANA", "LBS", "A3P", "BVP", "YYG", "291", "UAP",
				"0UH", "2DF", "6F7", "KAG", "BNX", "TTZ", "NMS", "M7A", "GCV", "1MA", "46D", "US1", "NPF", "LOX", "3SA",
				"DGC", "3AU", "WZ4", "TLB", "AP7", "PDX", "IDY", "US2", "6C2", "6S2", "49A", "VC7", "8S0", "17T", "MHG",
				"MMT", "GNX", "THP", "145", "M6D", "5HU", "RVM", "V3M", "T4S", "OGX", "2SA", "ABR", "Z4Y", "IAB", "Z4W",
				"LHH", "2LF", "6MZ", "G32", "NDU", "M7P", "HNV", "5IU", "PR5", "GLC", "E3C", "DYM", "PU",  "MDQ", "TTD",
				"TWD", "5LT", "Z16", "YYJ", "5L3", "CSL", "ENP", "ADR", "TX2", "GFL", "VTB", "XGR", "MAW", "U7B", "40J",
				"8AN", "DEL", "GBH", "GS9", "DFX", "GU9", "K5B", "5KQ", "DAN", "RBD", "GPU", "F7O", "GPO", "FSM", "3MG",
				"BM3", "OTU", "I5C", "TFE", "LER", "H53", "UFB", "Z6W", "147", "GL2", "18M", "P53", "50N", "4EN", "4U2",
				"GAA", "KG1", "BMN", "61J", "GLF", "2GF", "CGF", "SRA", "AHM", "8RO", "4PD", "4PE", "CEY", "HSH", "XTS",
				"293", "B1N", "Z9D", "1WA", "HSX", "GCD", "U37", "26V", "TLN", "EDA", "TU4", "P6P", "F3N", "JV4", "XNY",
				"FOX", "GU8", "XTY", "US4", "GLO", "XPB", "RCD", "9O4", "3LJ", "D5E", "G31", "B6D", "U1Y", "2MA", "7CV",
				"MRG", "2WP", "P2T", "4CQ", "WOO", "5TK", "SLB", "XFC", "3DR", "EEQ", "C7R", "RZM", "ABF", "96O", "EDC",
				"A39", "LGP", "6YR", "YX1", "49V", "LMU", "0AT", "MAG", "6LS", "F55", "2MU", "1TW", "LDY", "P9G", "KO1",
				"ABC", "BGM", "GU6", "MCU", "OTG", "F4Q", "5TH", "TUP", "RP3", "RUB", "79J", "TWA", "C7S", "3HD", "GS1",
				"OIP", "0U1", "GU1", "MGC", "Z6H", "F1X", "C4W", "57S", "SDG", "AC1", "GTM", "GAC", "UBD", "3MF", "USM",
				"4MF", "G",	  "56N", "G6P", "D1P", "6PZ", "ACX", "M5M", "T68", "GCS", "FFC", "95Z", "445", "DGI", "PMT",
				"CBK", "MAB", "GPV", "5FU", "ZHP", "U5M", "PA5", "PG7", "U4M", "WUN", "Z9H", "4SC", "JVA", "RY",  "CNP",
				"GMX", "MTU", "AET", "MAL", "6LA", "ONE", "YZ0", "DRT", "D33", "LHU", "U63", "8YN", "FIF", "A2L", "DGS",
				"U25", "6KH", "E6G", "AGC", "5IC", "FAI", "TM6", "TPG", "CE6", "FUF", "CBF", "UCD", "BGC", "B0D", "D0N",
				"PH5", "MAF", "EMP", "GQ1", "5JO", "MLR", "ZAD", "ODP", "KGM", "2SG", "2M8", "2OM", "LAI", "KOT", "PSG",
				"QPS", "7GP", "FCT", "LAO", "Z3L", "NLC", "SIA", "2OS", "MYG", "83Y", "Z4K", "XYF", "KDA", "F5H", "A5C",
				"IDG", "XAD", "6PG", "LKA", "RV7", "T0Q", "DNO", "ZB1", "T6P", "5MU", "9WN", "1GN", "6PY", "CFL", "YYM",
				"Z57", "UFT", "NM9", "7K2", "5SP", "MG5", "ZD0", "GL9", "GAT", "IPT", "MA7", "C32", "DDG", "UOB", "Z3K",
				"XUA", "ZTH", "T6D", "NF2", "0AP", "CEG", "6KL", "4SG", "GDP", "DRZ", "2JU", "XTH", "LXZ", "YG",  "1AP",
				"AVC", "0YT", "LCN", "GLW", "ZGU", "XLS", "DJB", "MAN", "PNG", "ZMR", "5EJ", "SGC", "XUL", "G4S", "XGP",
				"FVQ", "68Z", "JFZ", "A35", "NAG", "QSK", "DG8", "P2U", "TP1", "MDK", "UPV", "MUG", "TPC", "64P", "A44",
				"TCB", "U9G", "1MG", "HNW", "AWC", "C",	  "4JA", "TUG", "26Q", "2FE", "N9S", "YYB", "NBX", "TRE", "WIA",
				"GLP", "MEP", "HBZ", "RRY", "T49", "8GA", "TTI", "DZM", "U36", "MDV", "TUJ", "F74", "DXD", "DIG", "Z4S",
				"MVP", "4U1", "GXV", "9QV", "1TL", "3ME", "NGL", "T48", "C2L", "GFP", "AMU", "ARI", "9SM", "RHA", "BOG",
				"KBA", "ATL", "CB2", "ATM", "9S7", "5HC", "C36", "N7X", "C4J", "MIA", "X6X", "RNS", "R2G", "DDB", "D00",
				"G6S", "GOM", "BDZ", "GLB", "X1X", "6BG", "Z5L", "PQ1", "0MK", "HSQ", "IEM", "0KZ", "ABE", "G46", "SLM",
				"FNG", "EQ4", "RGG", "GLT", "2DG", "C37", "2H5", "JS2", "U2D", "J5B", "F6U", "ABT", "T39", "SGD", "6HG",
				"GU3", "46M", "MGS", "XLF", "Z8T", "BGP", "OEL", "0AM", "6OO", "US3", "23V", "DCZ", "NMT", "RBL", "RPC",
				"UPS", "MDA", "G38", "DOM", "SNG", "G20", "9QZ", "CRA", "C45", "EW3", "S8M", "IMC", "5TJ", "SSU", "T64",
				"QDK", "6IA", "2EG", "44S", "BTG", "IDU", "X4A", "H2P", "G47", "HOL", "DK4", "GMS", "7NU", "GAD", "LHO",
				"JLT", "KD5", "OYW", "0A",	"X2Y", "PSJ", "QSQ", "MDR", "8EX", "B1H", "3J4", "U9J", "1NA", "U2L", "C5L",
				"2HA", "A23", "G2F", "AHG", "CJB", "NNG", "UVX", "Z9L", "US5", "3S6", "UMX", "6KW", "A7E", "5KT", "EEN",
				"B4G", "9SP", "EXC", "A6U", "SUC", "X6Y", "MUB", "Z2D", "S81", "A43", "REL", "XTF", "BXY", "RIB", "ZBU",
				"FSW", "AQA", "CBR", "DEG", "SDH", "ZCZ", "AOG", "T38", "7JZ", "18D", "ROB", "PYO", "9VP", "UY1", "2AT",
				"KO2", "RVG", "GSR", "GLD", "5QP", "Z6J", "X0X", "KAK", "MGV", "S6M", "AD2", "AF2", "HSZ", "2IA", "510",
				"XAR", "DAF", "02I", "0DC", "2AU", "TDG", "07E", "B8Q", "TWY", "46Z", "5HM", "MFB", "DMU", "DR2", "TC",
				"15L", "G7M", "FYJ", "GC1", "6OG", "A",	  "FAG", "DUZ", "1CF", "6MC", "STZ", "GDA", "GYE", "FU4", "MN0",
				"OMC", "GCO", "GL0", "0V4", "C2S", "38J", "ZEE", "X2F", "ZGE", "2FI", "RP5", "4R1", "RAA", "ARW", "9OK",
				"CG1", "UY4", "JHM", "H2U", "4PC", "GZL", "T2S", "3GR", "LXB", "5HT", "VET", "HSG", "N4S", "FUY", "94O",
				"RNT", "NGK", "ADG", "DG",	"Z9E", "2JV", "GE1", "RAM", "SUS", "NP3", "KDO", "D3T", "ACG", "6MN", "0AD",
				"ENA", "9WZ", "RUS", "RHC", "BNG", "FCB", "25E", "MQG", "8Y9", "OKT", "9YW", "CR6", "63H", "XDX", "HSU",
				"XGU", "51N", "G3F", "GCT", "DNR", "GU4", "3BU", "M4C", "L1L", "GU5", "URD", "ERI", "ALL", "GL6", "BZG",
				"SC",  "TAF", "F7K", "RUG", "SUR", "RMP", "TCG", "5LS", "GUP", "CKB", "TQY", "4U3", "GSA", "SF6", "ALX",
				"2FG", "4GL", "3LR", "NYT", "G36", "3J3", "EAG", "89Y", "ME6", "6MI", "TA3", "HSY", "SUP", "AH8", "BMQ",
				"URX", "RR7", "GYU", "IRN", "TYU", "DBM", "31M", "56B", "SN5", "U2A", "NXD", "BZD", "RDP", "AFD", "Z3Q",
				"9QG", "QV4", "G42", "8LR", "8AG", "5IT", "YX0", "N1L", "HD4", "U97", "6FK", "5SA", "L6T", "TM9", "NGF",
				"93D", "TGY", "BRU", "GP0", "NAA", "UOA", "L6S", "GLS", "RT",  "0DT", "ZB0", "LTG", "IXD", "QIF", "S4A",
				"TMX", "CBI", "10C", "PPW", "6Y6", "LSM", "HSR", "GNS", "T0T", "5L2", "ZDO", "18O", "P4U", "4V5", "PUF",
				"SDY", "PUY", "CE8", "HTG", "B8W", "6OP", "9V9", "MMA", "TT",  "1SD", "BQY", "6LW", "MFO", "7K3", "4TA",
				"KDD", "6FU", "RP6", "12A", "XXM", "KFN", "NBG", "GX1", "F1P", "Y5P", "10M", "CMR", "RI2", "TG",  "U",
				"A2M", "7MG", "AFO", "M8C", "GL7", "E4P", "SID", "48Z", "1PR", "1S3", "0NZ", "YDR", "5DB", "HTM", "ZDM",
				"6KS", "MA6", "Y",	 "Z15", "SF9", "XCS", "O2Z", "4AC", "604", "XYT", "DGM", "6GB", "GCK", "UBR", "3DY",
				"NT1", "B2G", "S7P", "UR3", "TED", "GPM", "1FT", "SIO", "M6P", "DC",  "R1P", "B8N", "UPE", "20X", "GTE",
				"LAG", "AMG", "EGA", "0DA", "AAB", "GIV", "IDT", "BDF", "RAE", "5RP", "8MG", "62I", "RPA", "6HB", "U33",
				"D3",  "LMS", "Z9W", "8OQ", "UD5", "LRH", "XMM", "Z8H", "R5P", "FFX", "MA8", "K99", "BCW", "IU",  "GP1",
				"KDB", "F2T", "MJJ", "Z2T", "LCG", "2GL", "4N2", "5CG", "50L", "AFL", "OHU", "G8Z", "XIL", "PNA", "XCY",
				"XTR", "G25", "LSH", "BMA", "C42", "CP1", "FMF", "T41", "Z9K", "M2F", "YYH", "6DM", "PSU", "NTP", "4U0",
				"LKS", "64T", "PBT", "CTT", "TGP", "OMU", "6ZC", "F6H", "D6G", "2F8", "50A", "18Q", "AS",  "MNA", "1FC",
				"TGR", "MSX", "FRU", "CSM", "5KS", "DCT", "TTM", "NTT", "U9D", "M2G", "V3P", "FX1", "4GC", "2DM", "MCY",
				"8RJ", "GTR", "FMG", "URT", "SGS", "5OC", "CS8", "GYV", "S4U", "LCH", "NYM", "5DI", "IN1", "YRR", "MMN",
				"LMT", "RF5", "GCW", "TRV", "CSF", "TFU", "6FM", "75B", "NBY", "7GU", "TCY", "G1P", "LGU", "TFO", "ORP",
				"DKX", "0HX", "B8H", "GDO", "HSJ", "DPY", "6HC", "UDC", "FA2", "R2B", "BEM", "MDP", "CCC", "BT5", "GN1",
				"MF7", "3DO", "CJ1", "TFT", "8PY", "HMS", "NHF", "0U",	"FBP", "N5I", "DRM", "5TM", "BGH", "BTU", "RTV",
				"H1S", "HN1", "8LM", "CVC", "0XY", "G4P", "9SG", "3CM", "SHB", "ZB3", "GU2", "E1X", "V3L", "M1F", "TVD",
				"VG1", "U9M", "H6Z", "H1M", "MAV", "149", "05L", "GF2", "ARA", "F7R", "DI",	 "J4T", "4RS", "GYG", "16F",
				"RCE", "SOS", "RAT", "GPQ", "GYP", "B1P", "BM7", "DLG", "A38", "BG8", "T32", "B9H", "EBG", "G16", "6FC",
				"HDL", "DDA", "CT3", "DA",	"F58", "A5O", "C3X", "TS8", "OI7", "3TD", "4OC", "F4H", "126", "FMU", "JW5",
				"M3M", "A0K", "MG1", "OPM", "E3M", "YYQ", "BXP", "8B9", "XYZ", "R1X", "GAF", "U34", "E7G", "9WJ", "W9T",
				"TLC", "RRJ", "TGA", "26O", "AOS", "1LL", "CKP", "20S", "6GR", "9T1", "6K3", "RER", "GS",  "4UZ", "FK9",
				"5SE", "MAD", "LST", "KBG", "45A", "MUM", "JZR", "4QY", "12E", "BFN", "DCG", "SHG", "GRB", "PAV", "8AZ",
				"LAT", "UDP", "XCL", "MRH", "YCO", "M1G", "TYV", "Z9M", "2BU", "DSR", "DLD", "G2L", "FDQ", "FDG", "CDR",
				"4GP", "GRX", "5N6", "XUG", "Z5J", "FSI", "MGL", "IDS", "TEU", "AFR", "BFP", "GMB", "M3O", "0LP", "RIP",
				"KHP", "S6P", "AGH", "FSR", "CX2", "U31", "DRI", "GMH", "QCK", "BND", "NFG", "BS7", "MRP", "64K", "NTO",
				"IGU", "CBV", "MBF", "7SA", "GNE", "XXR", "G3I", "LWM", "GM0", "SCG", "ARE", "G2S", "LM2", "GCU", "M1P",
				"O2C", "MLB", "AY9", "TVS", "EIT", "EPG", "LVO", "XYB", "MBG", "0SP", "NM6", "2DR", "UCL", "MDJ", "QBT",
				"0AU", "TVG", "6HA", "R",	"GTK", "0C",  "GSS", "NDG", "5BU", "289", "LG",	 "7BG", "FUB", "FUD", "UEA",
				"EQV", "NRI", "SFU", "ZCY", "BCD", "8DT", "P",	 "FCA", "BOE", "ISX", "26Y", "PGN", "DR5", "8BA", "T23",
				"G33", "TGK", "ADX", "G4D", "MA3", "8AA", "BWG", "TVY", "TMR", "OKN", "MFU", "FKD", "9C1", "85Y", "GU0",
				"M55", "TW7", "0BD", "BBK", "BHG", "SPT", "AAL", "DT",	"SHD", "RY7", "TSP", "LGC", "SFJ", "CDW", "DFT",
				"LBT", "TC1", "B8T", "M3N", "A3A", "6UD", "NR1", "70U", "MBZ", "NDN", "NTF", "BG6", "3MK", "AFP", "GN4",
				"0WK", "AXP", "GDL", "XTL", "AXR", "CTR", "DFR", "O2G", "SG7", "CR1", "SSH", "ACR", "GUL", "A47", "ENQ",
				"EQP", "NED", "V71", "26M", "KDF", "QKH", "4DU", "BDP", "T3P", "SGA", "8OG", "4SU", "1S4", "G48", "D1M",
				"9CD", "S4C", "I57", "SCR", "M7B", "JLN", "UMS", "ETT", "ADA", "AH2", "2WS", "1DP", "MGA", "DR4", "U8V",
				"PPC", "RAF", "G49", "PYY", "Z4R", "9MR", "CTG", "DJE", "P1P", "LFC", "2M4", "66O", "GE3", "TAL", "TT7",
				"DAG", "KDR", "DOC", "1CC", "DFC", "DGO", "PGP", "22S", "KDN", "DPC", "MGQ", "NGA", "GH3", "ISD", "JRV",
				"23G", "125", "B7C", "URU", "T31", "DN",  "FUL", "PA1", "5GO", "ABD", "IDR", "C5X", "FHU", "RAO", "B9B",
				"LAH", "ZEL", "PSV", "TAG", "MA2", "A7C", "TVV", "49T", "GXL", "LPK", "5MC", "DDL", "32O", "73W", "LV2",
				"TWG", "DDN", "PNW", "EAN", "8GG", "475", "TWJ", "9SJ", "GUZ", "9AM", "18T", "TVM", "AZC", "N",	  "5FA",
				"E",   "UBI", "5PY", "GMU", "5CF", "92F", "MAT", "NCU", "T37", "24S", "BGL", "GAO", "BGN", "EDI", "0UB",
				"6KU", "SI3", "C49", "EJT", "LTM", "2DT", "045", "BXF", "AMN", "26W", "C46", "3R3", "2GS", "9GP", "D4M",
				"LCC", "8GP", "MNU", "TOC", "B7G", "5CM", "HDP", "ZDC", "MTR", "MUR", "3FM", "TUR", "IC",  "NSQ", "OX2",
				"MXZ", "B16", "AF1", "XYS", "ASO", "NGC", "0TS", "BO1", "FMO", "NGB", "5MM", "RFJ", "MDU", "THX", "LOG",
				"C3G", "I4U", "4NN", "T36", "2AR", "GMT", "MQT", "DLF", "T5S", "DGD", "SGN", "MFA", "63G", "FIX", "GL5",
				"RIA", "UAR", "NGS", "3MU", "O1G", "8PK", "FUC", "H6Q", "IG",  "LC",  "TA6", "E5G", "8FG", "A34", "GC9",
				"N6G", "FDP", "MTT", "RTP", "QUO", "S4G", "C4B", "DR3", "C3B", "GRF", "P8E", "2LA", "YO5", "P7G", "YKR",
				"TS",  "16O", "U8U", "5GF", "NG6", "A5L", "BDR", "G28", "XS2", "JSP", "UF2", "8YV", "S2M", "47C", "D3N",
				"GPW", "LAK", "XGL", "IDX", "1AR", "OAD", "SEJ", "0DG", "MBE", "ABL", "X",	 "TM5", "CEZ", "LTP", "B8K",
				"BRI", "C4S", "TDY", "SG4", "2FL", "49S", "YYR", "RSP", "C43", "PZU", "BMX", "5AT", "U2N", "ASU", "TXB",
				"IPN", "GDR", "S6G", "T6A", "RG1", "YJM", "U2P", "5NC", "AGL", "CTO", "NGZ", "A6G", "DVC", "6SA", "XXX",
				"X4S", "ATD", "NA1", "Z0F", "Z4U", "GN7", "VJ1" /*, "SOL" */ };
		return out;
	}

	TYPE get( const Dictionary & p_dict, const std::string & p_resname )
	{
		for ( uint it_type = 0; it_type < toUnderlying( TYPE::COUNT ); it_type++ )
		{
			auto & voc = p_dict.vocabularies[ it_type ];
			if ( voc.contains( p_resname ) )
			{
				return static_cast<TYPE>( it_type );
			}
		}
		return p_dict.fallbackAttribution;
	}

} // namespace VTX::Core::ChemDB::Category
