# Lib.
add_library(vtx_app)
vtx_configure_target(vtx_app)

file(GLOB_RECURSE HEADERS "${CMAKE_CURRENT_LIST_DIR}/../include/*")
file(GLOB_RECURSE SOURCES "${CMAKE_CURRENT_LIST_DIR}/../src/*")
file(GLOB_RECURSE HEADERS_VENDORS "${CMAKE_CURRENT_LIST_DIR}/../vendor/*hpp" "${CMAKE_CURRENT_LIST_DIR}/../vendor/*h")
target_sources(vtx_app
	PRIVATE ${SOURCES}
	PUBLIC FILE_SET public_headers TYPE HEADERS BASE_DIRS "${CMAKE_CURRENT_LIST_DIR}/../include" FILES ${HEADERS}
	PRIVATE FILE_SET vendors_headers TYPE HEADERS BASE_DIRS "${CMAKE_CURRENT_LIST_DIR}/../vendor" FILES ${HEADERS_VENDORS}
)

# Tests.
file(GLOB_RECURSE SOURCES_TEST "${CMAKE_CURRENT_LIST_DIR}/../test/*")
add_executable(vtx_app_test ${SOURCES_TEST})
set_property(TARGET vtx_app_test PROPERTY FOLDER "test")
vtx_configure_target(vtx_app_test)
if (VTX_RENDERER)
	vtx_link_cuda(vtx_app_test)
endif()

if (NOT DEFINED _VTX_APP_CONAN)
	target_link_libraries(vtx_app PUBLIC vtx_util)
	target_link_libraries(vtx_app PUBLIC vtx_core)
	target_link_libraries(vtx_app PUBLIC vtx_io)
	if (VTX_RENDERER)
		target_link_libraries(vtx_app PUBLIC vtx_renderer)
	endif()
	if (VTX_PYTHON_BINDING)
		target_link_libraries(vtx_app PUBLIC vtx_python_binding)
	endif()
	target_link_libraries(vtx_app_test PRIVATE vtx_util)
	target_link_libraries(vtx_app_test PRIVATE vtx_core)
	target_link_libraries(vtx_app_test PRIVATE vtx_io)
	if (VTX_RENDERER)
		target_link_libraries(vtx_app_test PRIVATE vtx_renderer)
	endif()
	if (VTX_PYTHON_BINDING)
		target_link_libraries(vtx_app_test PRIVATE vtx_python_binding)
	endif()
else()
	target_link_libraries(vtx_app PUBLIC vtx_util::vtx_util)
	target_link_libraries(vtx_app PUBLIC vtx_core::vtx_core)
	target_link_libraries(vtx_app PUBLIC vtx_io::vtx_io)
	if (VTX_RENDERER)
		target_link_libraries(vtx_app PUBLIC vtx_renderer::vtx_renderer)
	endif()
	if (VTX_PYTHON_BINDING)
		target_link_libraries(vtx_app PUBLIC vtx_python_binding::vtx_python_binding)
	endif()
	target_link_libraries(vtx_app_test PRIVATE vtx_util::vtx_util)
	target_link_libraries(vtx_app_test PRIVATE vtx_core::vtx_core)
	target_link_libraries(vtx_app_test PRIVATE vtx_io::vtx_io)
	if (VTX_RENDERER)
		target_link_libraries(vtx_app_test PRIVATE vtx_renderer::vtx_renderer)
	endif()
	if (VTX_PYTHON_BINDING)
		target_link_libraries(vtx_app_test PRIVATE vtx_python_binding::vtx_python_binding)
	endif()
endif()

target_link_libraries(vtx_app PRIVATE argparse::argparse)
target_link_libraries(vtx_app_test PRIVATE vtx_app)
target_link_libraries(vtx_app_test PRIVATE Catch2::Catch2WithMain)
if (VTX_PYTHON_BINDING)
	vtx_python_binding_copy_runtime(vtx_app_test)
endif()

# Vendor libs.
if(WIN32)
	set(VELOPACK_LIB "${CMAKE_CURRENT_LIST_DIR}/../vendor/velopack/lib-static/velopack_libc_win_x64_msvc.lib")
	target_link_libraries(vtx_app PRIVATE ntdll)
else()
	set(VELOPACK_LIB "${CMAKE_CURRENT_LIST_DIR}/../vendor/velopack/lib-static/libvelopack_libc_linux_x64_gnu.a")
endif()
target_link_libraries(vtx_app PRIVATE ${VELOPACK_LIB})

target_compile_definitions(vtx_app PRIVATE VTX_VERSION_MAJOR=${VTX_VERSION_MAJOR})
target_compile_definitions(vtx_app PRIVATE VTX_VERSION_MINOR=${VTX_VERSION_MINOR})
target_compile_definitions(vtx_app PRIVATE VTX_VERSION_PATCH=${VTX_VERSION_PATCH})
target_compile_definitions(vtx_app PUBLIC VTX_RENDERER=${VTX_RENDERER})
target_compile_definitions(vtx_app PUBLIC VTX_PYTHON_BINDING=${VTX_PYTHON_BINDING})

vtx_copy_directory(vtx_app_test "${CMAKE_CURRENT_LIST_DIR}/../test/data" "$<TARGET_FILE_DIR:vtx_app_test>/data")

include(CTest)
include(Catch)
catch_discover_tests(vtx_app_test DISCOVERY_MODE PRE_TEST PROPERTIES RESOURCE_LOCK vtx_app_test)
