@ECHO OFF
ECHO [VTX] BUILDING SOLUTION FOR VS2019 x64
cmake .. -B "../_windows" -G "Visual Studio 16 2019" -DCMAKE_GENERATOR_PLATFORM=x64 -DDEFINE_PRODUCTION=OFF -DBUILD_LIB=OFF .
ECHO [VTX] DONE
PAUSE