#ifndef __VTX_UI_ID__
#define __VTX_UI_ID__

#include <app/old/id.hpp>

// TODO rename this namespace to UI when all UI will be extracted from src (and remove UI IDs in src/id.hpp
namespace VTX::UI::ID
{
	namespace Window
	{
		// Base
		const App::Old::VTX_ID SCENE		= "SCENE";
		const App::Old::VTX_ID RENDER	= "RENDER";
		const App::Old::VTX_ID INSPECTOR = "INSPECTOR";
		const App::Old::VTX_ID CONSOLE	= "CONSOLE";
		const App::Old::VTX_ID SEQUENCE	= "SEQUENCE";
		// !V0.1
		// const VTX::App::Old::VTX_ID SELECTION	 = "SELECTION";
		const App::Old::VTX_ID SETTINGS	  = "SETTINGS";
		const App::Old::VTX_ID INFORMATION = "INFORMATION";

		// Tools
		const App::Old::VTX_ID STRUCTURAL_ALIGNMENT = "STRUCTURAL_ALIGNMENT";

	} // namespace Window
	namespace Input
	{
		const App::Old::VTX_ID MAIN_WINDOW	= "MAIN_WINDOW";
		const App::Old::VTX_ID RENDER_WIDGET = "OPENGL_WIDGET";

	} // namespace Input

	namespace View
	{
		const App::Old::VTX_ID MEASUREMENT_ON_MOLECULE = "MEASUREMENT_ON_MOLECULE";

		const App::Old::VTX_ID UI_MOLECULE_STRUCTURE			   = "MOLECULE_STRUCTURE";
		const App::Old::VTX_ID UI_MOLECULE_SEQUENCE			   = "MOLECULE_SEQUENCE";
		const App::Old::VTX_ID UI_MOLECULE					   = "MOLECULE";
		const App::Old::VTX_ID UI_CHAIN						   = "CHAIN";
		const App::Old::VTX_ID UI_RESIDUE					   = "RESIDUE";
		const App::Old::VTX_ID UI_ATOM						   = "ATOM";
		const App::Old::VTX_ID UI_PATH_LIST					   = "PATH_LIST";
		const App::Old::VTX_ID UI_PATH						   = "PATH";
		const App::Old::VTX_ID UI_VIEWPOINT					   = "VIEWPOINT";
		const App::Old::VTX_ID UI_SCENE_VIEWPOINT			   = "SCENE_VIEWPOINT";
		const App::Old::VTX_ID UI_SCENE_PATH					   = "SCENE_PATH";
		const App::Old::VTX_ID UI_SELECTION					   = "SELECTION";
		const App::Old::VTX_ID UI_SELECTION_SEQUENCE			   = "SELECTION_SEQUENCE";
		const App::Old::VTX_ID UI_SCENE_REPRESENTATION		   = "SCENE_REPRESENTATION";
		const App::Old::VTX_ID UI_SCENE_DISTANCE_LABEL		   = "SCENE_DISTANCE_LABEL";
		const App::Old::VTX_ID UI_SCENE_DISTANCE_TO_CYCLE_LABEL = "SCENE_DISTANCE_TO_CYCLE_LABEL";
		const App::Old::VTX_ID UI_SCENE_ANGLE_LABEL			   = "SCENE_ANGLE_LABEL";
		const App::Old::VTX_ID UI_SCENE_DIHEDRAL_ANGLE_LABEL	   = "SCENE_DIHEDRAL_ANGLE_LABEL";

		const App::Old::VTX_ID UI_INSPECTOR_MOLECULE_STRUCTURE		   = "INSPECTOR_MOLECULE_STRUCTURE";
		const App::Old::VTX_ID UI_INSPECTOR_CHAIN					   = "INSPECTOR_CHAIN";
		const App::Old::VTX_ID UI_INSPECTOR_RESIDUE					   = "INSPECTOR_RESIDUE";
		const App::Old::VTX_ID UI_INSPECTOR_ATOM						   = "INSPECTOR_ATOM";
		const App::Old::VTX_ID UI_INSPECTOR_REPRESENTATION			   = "INSPECTOR_REPRESENTATION";
		const App::Old::VTX_ID UI_INSPECTOR_INSTANTIATED_REPRESENTATION = "INSPECTOR_INSTANTIATED_REPRESENTATION";
		const App::Old::VTX_ID UI_INSPECTOR_VIEWPOINT				   = "INSPECTOR_VIEWPOINT";

		const App::Old::VTX_ID UI_MENU_VISUALIZATION_REPRESENTATION_LIBRARY = "MENU_VISUALIZATION_REPRESENTATION_LIBRARY";
		const App::Old::VTX_ID UI_REPRESENTATION_LIBRARY_COMBO_BOX		   = "REPRESENTATION_LIBRARY_COMBO_BOX";

		const App::Old::VTX_ID UI_RENDER_EFFECT_PRESET_LIBRARY			  = "RENDER_EFFECT_PRESET_LIBRARY";
		const App::Old::VTX_ID UI_RENDER_EFFECT_PRESET					  = "RENDER_EFFECT_PRESET";
		const App::Old::VTX_ID UI_RENDER_EFFECT_LIBRARY_COMBO_BOX		  = "RENDER_EFFECT_LIBRARY_COMBO_BOX";
		const App::Old::VTX_ID UI_MENU_VISUALIZATION_RENDER_EFFECT_LIBRARY = "MENU_VISUALIZATION_RENDER_EFFECT_LIBRARY";

		const App::Old::VTX_ID UI_REPRESENTATION_PRESET_LIBRARY = "REPRESENTATION_PRESET_LIBRARY";
		const App::Old::VTX_ID UI_REPRESENTATION_EDITOR_PRESET  = "REPRESENTATION_EDITOR_PRESET";

		const App::Old::VTX_ID UI_RENDER_MEASUREMENT_DISTANCE			= "RENDER_MEASUREMENT_DISTANCE";
		const App::Old::VTX_ID UI_RENDER_MEASUREMENT_DISTANCE_TO_CYCLE	= "RENDER_MEASUREMENT_DISTANCE_TO_CYCLE";
		const App::Old::VTX_ID UI_RENDER_MEASUREMENT_ANGLE				= "RENDER_MEASUREMENT_ANGLE";
		const App::Old::VTX_ID UI_RENDER_MEASUREMENT_DIHEDRAL_ANGLE		= "RENDER_MEASUREMENT_DIHEDRAL_ANGLE";
		const App::Old::VTX_ID UI_RENDER_MEASUREMENT_MEASURE_IN_PROGRESS = "RENDER_MEASUREMENT_MEASURE_IN_PROGRESS";

		const App::Old::VTX_ID UI_CAMERA_QUICK_ACCESS_ON_RENDER_EFFECT = "CAMERA_QUICK_ACCESS_ON_RENDER_EFFECT";

	} // namespace View

	namespace State
	{
		const VTX::App::Old::VTX_ID VISUALIZATION = "VISUALIZATION";
		const VTX::App::Old::VTX_ID PLAY			 = "PLAY";
		const VTX::App::Old::VTX_ID EXPORT		 = "EXPORT";
	} // namespace State

	namespace Controller
	{
		const VTX::App::Old::VTX_ID FREEFLY	   = "FREEFLY";
		const VTX::App::Old::VTX_ID TRACKBALL   = "TRACKBALL";
		const VTX::App::Old::VTX_ID ORBIT	   = "ORBIT";
		const VTX::App::Old::VTX_ID SHORTCUT	   = "SHORCUT";
		const VTX::App::Old::VTX_ID VESSEL	   = "VESSEL";
		const VTX::App::Old::VTX_ID PICKER	   = "PICKER";
		const VTX::App::Old::VTX_ID MEASUREMENT = "MEASUREMENT";
		const VTX::App::Old::VTX_ID MAIN_WINDOW = "MAIN_WINDOW";
	} // namespace Controller
} // namespace VTX::UI::ID

#endif
