include ("${CMAKE_CURRENT_LIST_DIR}/copy_data.cmake")
set(SOURCES " ")
file(GLOB_RECURSE SOURCES "${CMAKE_CURRENT_LIST_DIR}/../src/*")
add_executable(vtx_app_test ${SOURCES})

configure_target(vtx_app_test)

if (NOT DEFINED _VTX_APP_TEST_CONAN)
	target_link_libraries(vtx_app_test PUBLIC vtx_util)
	target_link_libraries(vtx_app_test PUBLIC vtx_renderer)
	target_link_libraries(vtx_app_test PUBLIC vtx_core)
	target_link_libraries(vtx_app_test PUBLIC vtx_io)
	target_link_libraries(vtx_app_test PUBLIC vtx_app)
	target_link_libraries(vtx_app_test PUBLIC EnTT::EnTT)
	target_link_libraries(vtx_app_test PUBLIC Catch2::Catch2WithMain)
else()
	target_link_libraries(vtx_app_test PRIVATE vtx_util::vtx_util)
	target_link_libraries(vtx_app_test PRIVATE vtx_renderer::vtx_renderer)
	target_link_libraries(vtx_app_test PRIVATE vtx_core::vtx_core)
	target_link_libraries(vtx_app_test PRIVATE vtx_io::vtx_io)
	target_link_libraries(vtx_app_test PRIVATE vtx_app::vtx_app)
	target_link_libraries(vtx_app_test PRIVATE EnTT::EnTT)
	target_link_libraries(vtx_app_test PRIVATE Catch2::Catch2WithMain)
endif()

catch_discover_tests(vtx_app_test)

vtx_copy_registered_data(vtx_app_test)