#include "molecule_sequence.hpp"

namespace VTX
{
	namespace View
	{
		namespace UI
		{
			void MoleculeSequence::_drawContent()
			{
				ImGui::Text(
					"LALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALA"
					"LALA"
					"LALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALA"
					"LALA"
					"LALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALA"
					"LALA"
					"LALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALA"
					"LALA"
					"LALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALA"
					"LALA"
					"LALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALALA"
					"LALA"
					"LALALALALALALALALALA" );
			}

		} // namespace UI

	} // namespace View
} // namespace VTX
