#version 450
#include "include/helper.glsl"

#ifndef LOCAL_SIZE_X
	#define LOCAL_SIZE_X 1
#endif
#ifndef LOCAL_SIZE_Y
	#define LOCAL_SIZE_Y 1
#endif
#ifndef LOCAL_SIZE_Z
	#define LOCAL_SIZE_Z 1
#endif
layout (local_size_x = LOCAL_SIZE_X, local_size_y = LOCAL_SIZE_Y, local_size_z = LOCAL_SIZE_Z) in;

// Uniforms.
uniform uint uSize;

// SSBO.
layout (std140, binding = 0) readonly buffer Positions
{
	vec4[] positions;
};

layout (std140, binding = 1) buffer Normals
{
	vec4[] normals;
};

layout (std430, binding = 2) readonly buffer Indices
{
	uint[] indices;
};

layout (std430, binding = 3) buffer Counters
{
	uint[] counters;
};

void main()
{
	uint hash = globalInvocationHash( gl_GlobalInvocationID, gl_NumWorkGroups, gl_WorkGroupSize );
	
	hash *= 3;
	if( hash >= uSize )
	{
		return;
	}

	const vec3 normal = cross(  vec3( positions[ indices[ hash + 1 ] ] - positions[ indices[ hash + 2 ] ] ),
								vec3( positions[ indices[ hash + 1 ] ] - positions[ indices[ hash + 0 ] ] ) );

	for( uint i = 0; i < 3; ++i )
	{
		normals[ indices [ hash + i ] ] += vec4( normalize( normal ), 1.f );
		atomicAdd( counters[ indices [ hash + i ] ], 1);
	}
}