#version 450
#include "include/grid.glsl"

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

// Uniforms.
uniform vec3	uGridSESWorldOrigin;
uniform uvec3	uGridSESSize;
uniform vec3	uGridSESCellSize;

// SSBO.
layout (std430, binding = 5) writeonly buffer TriangleValidities
{
	uint[] triangleValidities;
};

void main()
{
// Get corresponding ses grid data.
	const uvec3 sesGridPosition = gl_GlobalInvocationID;
	const uint sesGridHash = gridHash( sesGridPosition, uGridSESSize );
}