set(SOURCES " ")
file(GLOB_RECURSE SOURCES "${CMAKE_CURRENT_LIST_DIR}/../src/*")
add_executable(vtx_ui_test ${SOURCES})

configure_target(vtx_ui_test)

if (NOT DEFINED _VTX_UI_TEST_CONAN)
	target_link_libraries(vtx_ui_test PUBLIC vtx_util)
	target_link_libraries(vtx_ui_test PUBLIC vtx_core)
	target_link_libraries(vtx_ui_test PUBLIC vtx_renderer)
	target_link_libraries(vtx_ui_test PUBLIC vtx_io)
	target_link_libraries(vtx_ui_test PUBLIC vtx_app)
	target_link_libraries(vtx_ui_test PUBLIC vtx_python_binding)
	target_link_libraries(vtx_ui_test PUBLIC vtx_tool)
	target_link_libraries(vtx_ui_test PUBLIC PyTX)
	target_link_libraries(vtx_ui_test PUBLIC vtx_ui)
else()
	target_link_libraries(vtx_ui_test PRIVATE vtx_util::vtx_util)
	target_link_libraries(vtx_ui_test PRIVATE vtx_core::vtx_core)
	target_link_libraries(vtx_ui_test PRIVATE vtx_renderer::vtx_renderer)
	target_link_libraries(vtx_ui_test PRIVATE vtx_io::vtx_io)
	target_link_libraries(vtx_ui_test PRIVATE vtx_app::vtx_app)
	target_link_libraries(vtx_ui_test PRIVATE vtx_python_binding::vtx_python_binding)
	target_link_libraries(vtx_ui_test PRIVATE vtx_tool::vtx_tool)
	target_link_libraries(vtx_ui_test PRIVATE vtx_python_binding::PyTX)
	target_link_libraries(vtx_ui_test PRIVATE vtx_ui::vtx_ui)
endif()

target_link_libraries(vtx_ui_test PRIVATE pybind11::embed)
target_link_libraries(vtx_ui_test PRIVATE Catch2::Catch2WithMain)

target_compile_definitions(vtx_ui_test PRIVATE VTX_RENDERER_NO_OPENGL)

vtx_register_build_directory_copy("${CMAKE_CURRENT_LIST_DIR}/../data" "./data")
vtx_copy_registered_data(vtx_ui_test)

include(CTest)
include(Catch)
catch_discover_tests(vtx_ui_test)
