function(link_cuda p_target)
	include(CheckLanguage)
	check_language(CUDA)
	if (CMAKE_CUDA_COMPILER)
		find_package(CUDAToolkit)
		target_link_libraries(${p_target} PRIVATE CUDA::cudart)
	else()
		message(STATUS "CUDA not found")
	endif()
endfunction()