name: CMake Core

on:
  push:
    branches: [ "master", "dev", "dev-ndy", "dev-sge" ]
    paths: ['lib/core/**', '.github/workflows/cmake_core.yml']

env:
  CMAKELISTS_DIR: ${{github.workspace}}/lib/core

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.2
      
    - name: Create default profile
      run: conan profile detect
      
    - name: Create packages
      working-directory: ${{env.CMAKELISTS_DIR}}
      run:  |
        conan export ../util
        conan create . --build=missing --settings=compiler.cppstd=20
