name: CMake Tool

on:
  push:
    branches: [ "master", "dev", "dev-ndy", "dev-sge" ]
    paths: ['lib/tool/**', '.github/workflows/cmake_tool.yml']

env:
  CMAKELISTS_DIR: ${{github.workspace}}/lib/tool

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.2
      
    - name: Create default profile
      run: conan profile detect
      
    - name: Add custom remote
      run: |
        conan remote add --insecure cano7782 ${{ secrets.CONAN_SERVER_HOST }}
        conan remote login -p ${{ secrets.CONAN_SERVER_USER }} cano7782 ${{ secrets.CONAN_SERVER_PASSWORD }}
           
    - name: Create package
      working-directory: ${{env.CMAKELISTS_DIR}}
      run: |
        conan export ../util
        conan export ../core
        conan export ../io
        conan export ../renderer
        conan export ../app
        conan export ../python_binding
        conan export ../ui
        conan export tools/mdprep/external/gromacs
        conan export tools/mdprep
        conan create . --build=missing --settings=compiler.cppstd=20
    
    - name: Test
      working-directory: ${{env.CMAKELISTS_DIR}}
      run: |
        conan create test --build=missing --settings=compiler.cppstd=20
        conan create tools/mdprep/test --build=missing --settings=compiler.cppstd=20

    
    - name: Upload dependencies
      working-directory: ${{env.CMAKELISTS_DIR}}
      run: |
        conan upload eigen -r=cano7782
        conan upload dylib -r=cano7782
        