name: CMake Core

on:
  push:
    branches: [ "master", "dev", "dev-ndy", "dev-sge", "dev-vge"  ]
    paths: ['lib/core/**', '.github/workflows/cmake_core.yml']

env:
  CMAKELISTS_DIR: ${{github.workspace}}/lib/core

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
    - name: Set git to use CRLF
      run: |
        git config --global core.autocrlf true
        git config --global core.eol crlf
        
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.2
      
    - name: Create default profile
      run: conan profile detect
      
    - name: Add custom remote
      run: |
        conan remote add --insecure cano7782 ${{ secrets.CONAN_SERVER_HOST }}
        conan remote login -p ${{ secrets.CONAN_SERVER_PASSWORD }} cano7782 ${{ secrets.CONAN_SERVER_USER }}
 
    - name: Create package
      working-directory: ${{env.CMAKELISTS_DIR}}
      run: |
        conan export ../util
        conan create . --build=missing --settings=compiler.cppstd=20
