name: CMake IO

on:
  push:
    branches: [ "master", "dev", "dev-ndy", "dev-sge" ]
    paths: ['lib/io/**', '.github/workflows/cmake_io.yml']

env:
  CMAKELISTS_DIR: ${{github.workspace}}/lib/io

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.2
      
    - name: Create default profile
      run: conan profile detect --force

    - name: Configure packages
      working-directory: ${{env.CMAKELISTS_DIR}}
      run:  |
        conan editable add .
        conan editable add ${{github.workspace}}/lib/util
        conan editable add ${{github.workspace}}/lib/core

    - name: Build 
      working-directory: ${{env.CMAKELISTS_DIR}}
      run: conan build test --build=missing --build=editable --settings=compiler.cppstd=20
    
    - name: Test
      working-directory: ${{env.CMAKELISTS_DIR}}
      run: ctest --verbose 
