name: CMake Util

on:
  push:
    branches: [ "master", "dev", "dev-ndy", "dev-sge" ]
    paths: ['lib/util/**', '.github/workflows/cmake_util.yml']

env:
  CMAKELISTS_DIR: ${{github.workspace}}/lib/util

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.2
      
    - name: Create default profile
      run: conan profile detect
      
    - name: Add custom remote
      run: |
        conan remote add --insecure cano7782 ${{ secrets.CONAN_SERVER_HOST }}
        conan remote login -p ${{ secrets.CONAN_SERVER_USER }} cano7782 ${{ secrets.CONAN_SERVER_PASSWORD }}
        
    - name: Install dependencies
      working-directory: ${{env.CMAKELISTS_DIR}}
      run: conan install . --build=missing --settings=compiler.cppstd=20

    - name: Upload dependencies
      working-directory: ${{env.CMAKELISTS_DIR}}
      run: |
        conan upload glm -r=cano7782
        conan upload spdlog -r=cano7782
        conan upload nlohmann_json -r=cano7782
        conan upload magic_enum -r=cano7782
        conan upload cpr -r=cano7782
        conan upload fmt -r=cano7782
        conan upload zlib -r=cano7782
        conan upload libcurl -r=cano7782
      
    - name: Create package
      working-directory: ${{env.CMAKELISTS_DIR}}
      run: conan create . --settings=compiler.cppstd=20
        
    - name: Test
      working-directory: ${{env.CMAKELISTS_DIR}}
      run: conan create test --build=missing --settings=compiler.cppstd=20
      
    - name: Upload extra dependencies
      working-directory: ${{env.CMAKELISTS_DIR}}
      run: |
        conan upload catch2 -r=cano7782