name: CMake Renderer

on:
  push:
    branches: [ "master", "dev", "dev-ndy", "dev-sge" ]
    paths: ['lib/renderer/**', '.github/workflows/cmake_renderer.yml']

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  CMAKELISTS_DIR: ${{github.workspace}}/lib/renderer
  CMAKE_BUILD_DIR: out
  CMAKE_INSTALL_DIR: install
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, ubuntu-20.04]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    
    - uses: knicknic/os-specific-run@v1.0.4
      with:
        linux: sudo apt-get install -y libglu1-mesa-dev xorg-dev

    - name: Configure CMake
      working-directory: ${{env.CMAKELISTS_DIR}}
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B out -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{env.CMAKELISTS_DIR}}
      # Build your program with the given configuration
      run: cmake --build ${{env.CMAKE_BUILD_DIR}} --config ${{env.BUILD_TYPE}} --target VTX_RENDERER VTX_RENDERER_BENCH VTX_RENDERER_TEST

    - name: Test
      working-directory: ${{env.CMAKELISTS_DIR}}/${{env.CMAKE_BUILD_DIR}}
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}} --verbose
    
    - name: Install
      if: runner.os == 'Windows'
      working-directory: ${{env.CMAKELISTS_DIR}}/${{env.CMAKE_BUILD_DIR}}
      run: cmake --install . --config ${{env.BUILD_TYPE}} --prefix ${{env.CMAKELISTS_DIR}}/${{env.CMAKE_INSTALL_DIR}}
    - name: Install
      if: runner.os == 'Linux' || runner.os == 'macOS'
      working-directory: ${{env.CMAKELISTS_DIR}}/${{env.CMAKE_BUILD_DIR}}
      run: sudo cmake --install . --config ${{env.BUILD_TYPE}} --prefix ${{env.CMAKELISTS_DIR}}/${{env.CMAKE_INSTALL_DIR}}

    - uses: actions/upload-artifact@v3
      with:
        name: VTXRendererBench_${{runner.os}}
        path: ${{env.CMAKELISTS_DIR}}/${{env.CMAKE_INSTALL_DIR}}/VTXRendererBench
      
