name: Lib App

on:
  push:
    branches: [ "master", "dev", "dev-sge", "dev-vge" ]
    paths: ['lib/app/**', '.github/workflows/lib_app.yml']
  workflow_dispatch:
      inputs:
        build_type:
          description: 'Build type'
          required: true
          default: 'Release'
          type: choice
          options:
          - Debug
          - Release

env:
  LIB_DIR: ${{github.workspace}}/lib
  BUILD_TYPE: ${{ inputs.build_type || 'Release' }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2022
            conan_cppstd: '20'
          - os: ubuntu-22.04
            conan_cppstd: 'gnu20'
          - os: windows-latest
            conan_cppstd: '20'
          - os: ubuntu-latest
            conan_cppstd: 'gnu20'
      fail-fast: false

    steps:
    - name: Set git to use CRLF
      if: runner.os == 'Windows'
      run: |
        git config --global core.autocrlf true
        git config --global core.eol crlf
        
    - uses: actions/checkout@v6.0.2
      with:
        submodules: recursive
        
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.2
      
    - name: Create default profile
      run: conan profile detect --force

    - name: Add custom remote
      run: |
        conan remote add vtx ${{ secrets.CONAN_SERVER_HOST }}
        conan remote login -p ${{ secrets.CONAN_SERVER_PASSWORD }} vtx ${{ secrets.CONAN_SERVER_USER }}

    - name: Export local packages
      working-directory: ${{env.LIB_DIR}}
      run: |
        conan export util
        conan export core
        conan export io
        conan export renderer
        conan export python_binding

    - name: Install dependencies
      working-directory: ${{env.LIB_DIR}}
      shell: bash
      run: |
        conan install app -b missing \
          -s build_type=${{env.BUILD_TYPE}} \
          -s compiler.cppstd=${{ matrix.conan_cppstd }} \
          -o vtx_app/*:test=True \
          -c tools.system.package_manager:mode=install \
          -c tools.system.package_manager:sudo=True

    - name: Upload dependencies
      working-directory: ${{env.LIB_DIR}}
      run: |
        conan upload entt -r=vtx

    - name: Create package
      working-directory: ${{env.LIB_DIR}}
      shell: bash
      run: |
        conan create app -b missing \
          -s build_type=${{env.BUILD_TYPE}} \
          -s compiler.cppstd=${{ matrix.conan_cppstd }} \
          -o vtx_app/*:test=True \
          -c tools.system.package_manager:mode=install \
          -c tools.system.package_manager:sudo=True