name: Lib Renderer

on:
  push:
    branches: [ "master", "dev", "dev-sge", "dev-vge" ]
    paths: ['lib/renderer/**', '.github/workflows/lib_renderer.yml']
  workflow_dispatch:
      inputs:
        build_type:
          description: 'Build type'
          required: true
          default: 'Release'
          type: choice
          options:
          - Debug
          - Release
        cuda_version:
          description: 'CUDA version'
          required: false
          default: '13.2.0'
        cuda_arch:
          description: 'Cuda architectures'
          required: false
          default: "75;80;86;87;89;90;100;120"

env:
  LIB_DIR: ${{github.workspace}}/lib
  BUILD_TYPE: ${{ inputs.build_type || 'Release' }}
  CUDA_VERSION: ${{ inputs.cuda_version }}
  CUDA_ARCH: ${{ inputs.cuda_arch }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2022
            conan_cppstd: '20'
          - os: ubuntu-22.04
            conan_cppstd: 'gnu20'
          - os: windows-latest
            conan_cppstd: '20'
          - os: ubuntu-latest
            conan_cppstd: 'gnu20'
          - os: windows-11-arm
            conan_cppstd: '20'
          - os: ubuntu-22.04-arm
            conan_cppstd: 'gnu20'
          - os: macos-15-intel
            conan_cppstd: '20'
          - os: macos-15
            conan_cppstd: '20'
      fail-fast: false

    steps:
    - name: Set git to use CRLF
      if: runner.os == 'Windows'
      run: |
        git config --global core.autocrlf true
        git config --global core.eol crlf
        
    - uses: actions/checkout@v6.0.2
      with:
        submodules: recursive   
        
    - name: Setup Conan
      uses: conan-io/setup-conan@v1.3.0
      with:
        use_venv: true
        profile_detect: true

    - name: Add custom remote
      run: |
        conan remote add vtx ${{ secrets.CONAN_SERVER_HOST }}
        conan remote login -p ${{ secrets.CONAN_SERVER_PASSWORD }} vtx ${{ secrets.CONAN_SERVER_USER }}

    - name: Install CUDA Toolkit
      if: env.CUDA_VERSION != ''
      uses: Jimver/cuda-toolkit@v0.2.32
      id: cuda-toolkit
      with:
        cuda: ${{ env.CUDA_VERSION }}
        method: network
        linux-local-args: '["--toolkit"]'
    
    - name: Setup CUDA environment
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          CUDA_PATH_WIN="$(cygpath -m "$CUDA_PATH")"
          CUDA_PATH_UNIX="$(cygpath -u "$CUDA_PATH")"

          NVCC="$CUDA_PATH_WIN/bin/nvcc.exe"
          CUDA_BIN="$CUDA_PATH_UNIX/bin"

        else
          CUDA_PATH_WIN="$CUDA_PATH"
          CUDA_PATH_UNIX="$CUDA_PATH"

          NVCC="$CUDA_PATH/bin/nvcc"
          CUDA_BIN="$CUDA_PATH/bin"
        fi

        echo "CUDA_PATH=$CUDA_PATH_WIN"
        echo "CUDA_BIN=$CUDA_BIN"
        echo "NVCC=$NVCC"

        "$NVCC" --version

        echo "$CUDA_BIN" >> "$GITHUB_PATH"

        echo "CUDA_PATH=$CUDA_PATH_WIN" >> "$GITHUB_ENV"
        echo "CUDAToolkit_ROOT=$CUDA_PATH_WIN" >> "$GITHUB_ENV"
        echo "CUDACXX=$NVCC" >> "$GITHUB_ENV"

    - name: Check CUDA
      if: env.CUDA_VERSION != ''
      shell: bash
      run: |
        echo "CUDA_PATH=$CUDA_PATH"
        ls "$CUDA_PATH/bin" || true
        "$CUDA_PATH/bin/nvcc.exe" --version
        nvcc --version

    - name: Create package
      working-directory: ${{env.LIB_DIR}}
      shell: bash
      run: |
        CUDA_ARCH_OPTION=()
        if [ -n "${CUDA_ARCH}" ]; then
          CUDA_ARCH_OPTION=(-o "vtx_renderer/*:cuda_arch=${CUDA_ARCH}")
        fi

        conan export util
        conan export core
        conan create renderer -b missing \
          -s build_type=${{env.BUILD_TYPE}} \
          -s compiler.cppstd=${{ matrix.conan_cppstd }} \
          -o vtx_renderer/*:test=True \
          "${CUDA_ARCH_OPTION[@]}" \
          -c tools.system.package_manager:mode=install \
          -c tools.system.package_manager:sudo=True \
          -c tools.cmake.cmaketoolchain:extra_variables="{\"CMAKE_CUDA_COMPILER\":\"$CUDACXX\",\"CUDAToolkit_ROOT\":\"$CUDAToolkit_ROOT\"}" 
