name: Lib Util

on:
  push:
    branches: [ "master", "dev", "dev-sge", "dev-vge" ]
    paths: ['lib/util/**', '.github/workflows/lib_util.yml']
  workflow_dispatch:
      inputs:
        build_type:
          description: 'Build type'
          required: true
          default: 'Release'
          type: choice
          options:
          - Debug
          - Release

env:
  LIB_DIR: ${{github.workspace}}/lib
  BUILD_TYPE: ${{ inputs.build_type || 'Release' }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2022
            conan_cppstd: '20'
          - os: ubuntu-22.04
            conan_cppstd: 'gnu20'
          - os: windows-latest
            conan_cppstd: '20'
          - os: ubuntu-latest
            conan_cppstd: 'gnu20'
          - os: windows-11-arm
            conan_cppstd: '20'
          - os: ubuntu-22.04-arm
            conan_cppstd: 'gnu20'
          - os: macos-15-intel
            conan_cppstd: '20'
          - os: macos-15
            conan_cppstd: '20'
      fail-fast: false

    steps:
    - name: Set git to use CRLF
      if: runner.os == 'Windows'
      run: |
        git config --global core.autocrlf true
        git config --global core.eol crlf
        
    - uses: actions/checkout@v6.0.2
      with:
        submodules: recursive
        
    - name: Setup Conan
      uses: conan-io/setup-conan@v1.3.0
      with:
        use_venv: true
        profile_detect: true
      
    - name: Add custom remote
      run: |
        conan remote add vtx ${{ secrets.CONAN_SERVER_HOST }} --index 0
        conan remote login -p ${{ secrets.CONAN_SERVER_PASSWORD }} vtx ${{ secrets.CONAN_SERVER_USER }}
           
    - name: Install dependencies
      working-directory: ${{env.LIB_DIR}}
      shell: bash
      run: |
        conan install util -b missing \
          -s build_type=${{env.BUILD_TYPE}} \
          -s compiler.cppstd=${{ matrix.conan_cppstd }} \
          -o vtx_util/*:test=True

    - name: Upload dependencies
      working-directory: ${{env.LIB_DIR}}
      run: |
        conan upload glm -r=vtx
        conan upload spdlog -r=vtx
        conan upload magic_enum -r=vtx
        conan upload nlohmann_json -r=vtx
        conan upload entt -r=vtx
        conan upload cpr -r=vtx
        conan upload stb -r=vtx
        conan upload fmt -r=vtx
        conan upload zlib -r=vtx
        conan upload libcurl -r=vtx
        conan upload openssl -r=vtx
        conan upload platformfolders -r=vtx
        conan upload catch2 -r=vtx

    - name: Create package
      working-directory: ${{env.LIB_DIR}}
      shell: bash
      run: |
        conan create util -b missing \
          -s build_type=${{env.BUILD_TYPE}} \
          -s compiler.cppstd=${{ matrix.conan_cppstd }} \
          -o vtx_util/*:test=True
