name: Lib UI

on:
  push:
    branches: [ "master", "dev", "dev-ndy", "dev-sge", "dev-vge" ]
    paths: ['lib/ui/qt/**', '.github/workflows/lib_ui_qt.yml']

env:
  LIB_DIR: ${{github.workspace}}/lib

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, ubuntu-22.04, windows-latest, ubuntu-latest]
      fail-fast: false

    steps:
    - name: Set git to use CRLF
      run: |
        git config --global core.autocrlf true
        git config --global core.eol crlf

    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
        
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.2
      
    - name: Create default profile
      run: conan profile detect
      
    - name: Add custom remote
      run: |
        conan remote add --insecure cano7782 ${{ secrets.CONAN_SERVER_HOST }}
        conan remote login -p ${{ secrets.CONAN_SERVER_PASSWORD }} cano7782 ${{ secrets.CONAN_SERVER_USER }}
           
    - name: Create package
      working-directory: ${{env.LIB_DIR}}
      run: |
        conan export util
        conan export core
        conan export io
        conan export renderer
        conan export app
        conan export python_binding
        conan create ui/qt -b missing -s compiler.cppstd=20 -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True
    
    - name: Upload dependencies
      working-directory: ${{env.LIB_DIR}}
      run: |
        conan upload qt -r=cano7782
