name: Lib Python Binding
 
on:
  push:
    branches: [ "master", "dev", "dev-sge", "dev-vge" ]
    paths: ['lib/python_binding/**', '.github/workflows/lib_python_binding.yml']
  workflow_dispatch:
      inputs:
        build_type:
          description: 'Build type'
          required: true
          default: 'Release'
          type: choice
          options:
          - Debug
          - Release
        python_version:
          description: 'Python version (override)'
          required: false

env:
  LIB_DIR: ${{github.workspace}}/lib
  BUILD_TYPE: ${{ inputs.build_type || 'Release' }}
  PYTHON_VERSION: ${{ inputs.python_version }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2022
            conan_cppstd: '20'
          - os: ubuntu-22.04
            conan_cppstd: 'gnu20'
          - os: windows-latest
            conan_cppstd: '20'
          - os: ubuntu-latest
            conan_cppstd: 'gnu20'
          - os: windows-11-arm
            conan_cppstd: '20'
          - os: ubuntu-22.04-arm
            conan_cppstd: 'gnu20'
          - os: macos-15-intel
            conan_cppstd: '20'
          - os: macos-15
            conan_cppstd: '20'
      fail-fast: false

    steps:
    - name: Set git to use CRLF
      if: runner.os == 'Windows'
      run: |
        git config --global core.autocrlf true
        git config --global core.eol crlf

    - uses: actions/checkout@v6.0.2
      with:
        submodules: recursive

    - name: Setup Conan
      uses: conan-io/setup-conan@v1.3.0
      with:
        use_venv: true
        profile_detect: true

    - name: Add custom remote
      run: |
        conan remote add vtx ${{ secrets.CONAN_SERVER_HOST }}
        conan remote login -p ${{ secrets.CONAN_SERVER_PASSWORD }} vtx ${{ secrets.CONAN_SERVER_USER }}

    - name: Export local packages
      working-directory: ${{env.LIB_DIR}}
      run: |
        conan export util
        conan export core
        conan export io
        conan export renderer

    - name: Install dependencies
      working-directory: ${{env.LIB_DIR}}
      shell: bash
      run: |
        PYTHON_VERSION_OPTION=()
        if [ -n "${PYTHON_VERSION}" ]; then
          PYTHON_VERSION_OPTION=(-o "vtx_python_binding/*:python_version=${PYTHON_VERSION}")
        fi

        conan install python_binding -b missing \
          -s build_type=${{env.BUILD_TYPE}} \
          -s compiler.cppstd=${{ matrix.conan_cppstd }} \
          -o vtx_python_binding/*:test=True \
          "${PYTHON_VERSION_OPTION[@]}" \
          -c tools.system.package_manager:mode=install \
          -c tools.system.package_manager:sudo=True

    - name: Upload dependencies
      working-directory: ${{env.LIB_DIR}}
      run: |
        conan upload pybind11 -r=vtx
        conan upload cpython -r=vtx
        conan upload mpdecimal -r=vtx
        conan upload sqlite3 -r=vtx

    - name: Create package
      working-directory: ${{env.LIB_DIR}}
      shell: bash
      run: |
        PYTHON_VERSION_OPTION=()
        if [ -n "${PYTHON_VERSION}" ]; then
          PYTHON_VERSION_OPTION=(-o "vtx_python_binding/*:python_version=${PYTHON_VERSION}")
        fi

        conan create python_binding -b missing \
          -s build_type=${{env.BUILD_TYPE}} \
          -s compiler.cppstd=${{ matrix.conan_cppstd }} \
          -o vtx_python_binding/*:test=True \
          "${PYTHON_VERSION_OPTION[@]}" \
          -c tools.system.package_manager:mode=install \
          -c tools.system.package_manager:sudo=True
