name: Lib UI

on:
  push:
    branches: [ "master", "dev", "dev-sge", "dev-vge" ]
    paths: ['lib/ui/qt/**', '.github/workflows/lib_ui_qt.yml']
  workflow_dispatch:
      inputs:
        build_type:
          description: 'Build type'
          required: true
          default: 'Release'
          type: choice
          options:
          - Debug
          - Release

env:
  LIB_DIR: ${{ github.workspace }}/lib
  BUILD_TYPE: ${{ inputs.build_type || 'Release' }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2022
            conan_cppstd: '20'
          - os: ubuntu-22.04
            conan_cppstd: 'gnu20'
          - os: windows-latest
            conan_cppstd: '20'
          - os: ubuntu-latest
            conan_cppstd: 'gnu20'
          # - os: windows-11-arm
          #   conan_cppstd: '20'
          # - os: ubuntu-22.04-arm
          #   conan_cppstd: 'gnu20'
          # - os: macos-15-intel
          #   conan_cppstd: '20'
          # - os: macos-15
          #   conan_cppstd: '20'
      fail-fast: false

    steps:
    - name: Set git to use CRLF
      if: runner.os == 'Windows'
      run: |
        git config --global core.autocrlf true
        git config --global core.eol crlf
        
    - uses: actions/checkout@v6.0.2
      with:
        submodules: recursive
        
    - name: Setup Conan
      uses: conan-io/setup-conan@v1.3.0
      with:
        use_venv: true
        profile_detect: true
      
    - name: Add custom remote
      run: |
        conan remote add vtx ${{ secrets.CONAN_SERVER_HOST }} --index 0
        conan remote login -p ${{ secrets.CONAN_SERVER_PASSWORD }} vtx ${{ secrets.CONAN_SERVER_USER }}

    - name: Export local packages
      working-directory: ${{env.LIB_DIR}}
      run: |
        conan export util
        conan export core
        conan export io
        conan export renderer
        conan export app
        conan export python_binding

    - name: Install dependencies
      working-directory: ${{env.LIB_DIR}}
      shell: bash
      run: |
        conan install ui/qt -b missing \
          -s build_type=${{ env.BUILD_TYPE }} \
          -s compiler.cppstd=${{ matrix.conan_cppstd }} \
          -c tools.system.package_manager:mode=install \
          -c tools.system.package_manager:sudo=True

    - name: Upload dependencies
      working-directory: ${{env.LIB_DIR}}
      run: |
        conan upload brotli -r=vtx
        conan upload bzip2 -r=vtx
        conan upload double-conversion -r=vtx
        conan upload freetype -r=vtx
        conan upload libjpeg -r=vtx
        conan upload libpng -r=vtx
        conan upload openssl -r=vtx
        conan upload pcre2 -r=vtx
        conan upload qt -r=vtx
        conan upload zlib -r=vtx

    - name: Upload Linux dependencies
      if: runner.os == 'Linux'
      working-directory: ${{env.LIB_DIR}}
      run: |
        conan upload dbus -r=vtx
        conan upload expat -r=vtx
        conan upload fontconfig -r=vtx
        conan upload libffi -r=vtx
        conan upload libiconv -r=vtx
        conan upload libxml2 -r=vtx
        conan upload wayland -r=vtx
        conan upload xkbcommon -r=vtx

    - name: Create package
      working-directory: ${{env.LIB_DIR}}
      shell: bash
      run: |
        conan create ui/qt -b missing \
          -s build_type=${{ env.BUILD_TYPE }} \
          -s compiler.cppstd=${{ matrix.conan_cppstd }} \
          -c tools.system.package_manager:mode=install \
          -c tools.system.package_manager:sudo=True
