name: Tool MdPrep

on:
  push:
    branches: [ "master", "dev", "dev-sge", "dev-vge" ]
    paths: ['tool/mdprep/**', '.github/workflows/tool_mdprep.yml']

env:
  ROOT_DIR: ${{github.workspace}}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-22.04, macos-12]
      fail-fast: false

    steps:
    - name: Set git to use CRLF
      run: |
        git config --global core.autocrlf true
        git config --global core.eol crlf
        
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.2
      
    - name: Create default profile
      run: conan profile detect --force

    - name: Add custom remote
      run: |
        conan remote add --insecure cano7782 ${{ secrets.CONAN_SERVER_HOST }}
        conan remote login -p ${{ secrets.CONAN_SERVER_PASSWORD }} cano7782 ${{ secrets.CONAN_SERVER_USER }}

    - name: Create package
      working-directory: ${{env.ROOT_DIR}}
      run:  |
        conan export lib/util
        conan export lib/core
        conan export lib/io
        conan export lib/renderer
        conan export lib/app
        conan export lib/ui/qt
        conan create tool/mdprep -b missing -s compiler.cppstd=20 -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True -o vtx_tool_mdprep/*:test=True
 
#    - name: Upload dependencies
#      working-directory: ${{env.ROOT_DIR}}
#      run: |
#        conan upload mydep -r=cano7782